scalar DateTimeISO

type Mutation {
  logout: String!
  registerUser(input: RegisterUserInput!): String!
  signInWithEmailAndPassword(input: SignInWithEmailAndPasswordInput!): Boolean!
  verifyVerificationLink(input: VerifyVerificationLinkInput!): String!
}

type Query {
  getCurrentUser: User
}

input RegisterUserInput {
  displayName: String!
  email: String!
  password: String!
}

input SignInWithEmailAndPasswordInput {
  email: String!
  password: String!
}

type User {
  createdAt: DateTimeISO!
  description: String
  displayName: String
  email: String!
  emailVerificationStatus: String!
  photoUrl: String
  userId: String!
}

input VerifyVerificationLinkInput {
  token: String!
}
