export { auditColumns, idColumn } from "@/db/columns";
export {
  type Client,
  type ClientGrantType,
  type ClientRedirectUri,
  type ClientScope,
  type Grant,
  type Identity,
  type IdentityProfile,
  type NewClient,
  type NewClientGrantType,
  type NewClientRedirectUri,
  type NewClientScope,
  type NewGrant,
  type NewIdentity,
  type NewIdentityProfile,
  type NewScope,
  type Scope,
  ClientGrantTypes,
  ClientGrantTypesRelations,
  ClientRedirectUris,
  ClientRedirectUrisRelations,
  ClientScopes,
  ClientScopesRelations,
  Clients,
  ClientsRelations,
  Grants,
  GrantsRelations,
  Identities,
  IdentitiesRelations,
  IdentityProfiles,
  IdentityProfilesRelations,
  Scopes,
  ScopesRelations,
} from "@/db/tables";
