export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  HttpServer: Symbol.for("IHttpServer"),
  RedisClient: Symbol.for("RedisClient"),
  ImageProcessingQueue: Symbol.for("ImageProcessingQueue"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  AttachmentService: Symbol.for("AttachmentService"),
  AttachmentRepository: Symbol.for("IAttachmentRepository"),
  AttachmentUploadRepository: Symbol.for("IAttachmentUploadRepository"),
  AttachmentUploadService: Symbol.for("IAttachmentUploadService"),
  ObjectStorage: Symbol.for("IObjectStorage"),
  IdentityRepository: Symbol.for("IIdentityRepository"),
  TenantRepository: Symbol.for("ITenantRepository"),
  AttachmentIdentitySyncConsumer: Symbol.for("AttachmentIdentitySyncConsumer"),
  AttachmentTenantSyncConsumer: Symbol.for("AttachmentTenantSyncConsumer"),
  AttachmentScannedConsumer: Symbol.for("AttachmentScannedConsumer"),
};
