DROP TABLE IF EXISTS access_tokens;
CREATE TABLE IF NOT EXISTS access_tokens (
  id UUID DEFAULT uuid_generate_v4() NOT NULL,
  user_id UUID NOT NULL, 
  token_value TEXT NOT NULL,
  status TEXT NOT NULL,
  expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,

  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);