export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  IdentityRepository: Symbol.for("IIdentityRepository"),
  IdentitySyncConsumer: Symbol.for("IdentitySyncConsumer"),
  MeService: Symbol.for("IMeService"),
  BrandRepository: Symbol.for("IBrandRepository"),
  BrandService: Symbol.for("IBrandService"),
  CategoryRepository: Symbol.for("ICategoryRepository"),
  CategoryService: Symbol.for("ICategoryService"),
  UnitRepository: Symbol.for("IUnitRepository"),
  UnitService: Symbol.for("IUnitService"),
  ProductRepository: Symbol.for("IProductRepository"),
  ProductUnitRepository: Symbol.for("IProductUnitRepository"),
  ProductService: Symbol.for("IProductService"),
} as const;
