mutation Logout {
  logout
}

mutation RegisterUser($input: RegisterUserInput!) {
  registerUser(input: $input)
}

mutation SignInWithEmailAndPassword($input: SignInWithEmailAndPasswordInput!) {
  signInWithEmailAndPassword(input: $input)
}

mutation VerifyVerificationLink($input: VerifyVerificationLinkInput!) {
  verifyVerificationLink(input: $input)
}

query GetCurrentUser {
  getCurrentUser {
    userId
    email
    emailVerificationStatus
    createdAt
    displayName
    photoUrl
    description
  }
}
