mutation CreateIssue($input: CreateIssueInput!) {
  createIssue(input: $input)
}

mutation UpdateIssue($input: UpdateIssueInput!) {
  updateIssue(input: $input)
}

query FindIssue($findIssueId: String!) {
  findIssue(id: $findIssueId) {
    id
    description
    project {
      id
      name
    }
    parentIssue {
      id
      name
    }
    name
    statusId
    priority
  }
}

query FindProjectIssues($projectId: String!) {
  findProjectIssues(projectId: $projectId) {
    description
    id
    name
    statusId
    priority
  }
}

query FindSubIssues($input: FindIssuesInput!) {
  findSubIssues(input: $input) {
    description
    id
    name
  }
}
