export enum Errors {
  ERR_DATABASE = "ERR_DATABASE",
  ERR_CONNECTION_REFUSED = "ERR_CONNECTION_REFUSED",
  ERR_QUERY_EXECUTION = "ERR_QUERY_EXECUTION",
  ERR_MISSING_DATASOURCE = "ERR_MISSING_DATASOURCE",
  ERR_TRANSACTION_EXECUTION = "ERR_TRANSACTION_EXECUTION",

  ERR_UTILITY = "ERR_UTILITY",

  ERR_RESPONSE = "ERR_RESPONSE",
  ERR_BAD_REQUEST = "ERR_BAD_REQUEST",
  ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED",
  ERR_FORBIDDEN = "ERR_FORBIDDEN",
  ERR_NOT_FOUND = "ERR_NOT_FOUND",
  ERR_UNSUPPORTED_MEDIA_TYPE = "ERR_UNSUPPORTED_MEDIA_TYPE",
  ERR_INTERNAL_SERVER = "ERR_INTERNAL_SERVER",
  ERR_CONFLICT = "ERR_CONFLICT",

  ERR_VALIDATION = "ERR_VALIDATION",
  ERR_MISSING_FIELD = "ERR_MISSING_FIELD",
  ERR_REQUIRED_FIELD = "ERR_REQUIRED_FIELD",
  ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS",
  ERR_EMAIL_NOT_VERIFIED = "ERR_EMAIL_NOT_VERIFIED",
  ERR_VERSION_MISMATCH = "ERR_VERSION_MISMATCH",
  ERR_MISSING_ENFORCER = "ERR_MISSING_ENFORCER",
  ERR_MISSING_SENDER = "ERR_MISSING_SENDER",
  ERR_EMAIL_ALREADY_SENT = "ERR_EMAIL_ALREADY_SENT",

  ERR_PROJECT_NOT_FOUND = "ERR_PROJECT_NOT_FOUND",
}
