query GetPlatformRole($id: String!) {
  getPlatformRole(id: $id) {
    id
    key
    name
    description
    isSystem
    createdAt
    updatedAt
    capabilities {
      id
      key
      service
      resource
      action
    }
  }
}
