query GetPlatformRole($id: String!) {
  getPlatformRole(id: $id) {
    id
    key
    name
    description
    isSystem
    createdAt
    updatedAt
    permissions {
      key
      namespace
      permission
    }
  }
}
