services:
  auth-postgres:
    image: postgres:latest
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5431:5432"
    volumes:
      - ../data/auth-postgres-data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - max_connections=1000

  issue-tracker-postgres:
    image: postgres:latest
    container_name: issue-tracker-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/issue-tracker-postgres-data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - max_connections=1000

  mail-postgres:
    image: postgres:latest
    container_name: mail-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ../data/mail-postgres-data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - max_connections=1000
  mail-postgres-test:
    image: postgres:latest
    container_name: mail-postgres-test
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15433:5432"
    command:
      - postgres
      - -c
      - max_connections=1000

  attachment-postgres:
    image: postgres:latest
    container_name: attachment-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - ../data/attachment-postgres-data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - max_connections=1000

  attachment-redis:
    image: redis:8.0-M02-alpine
    container_name: attachment-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - 6380:6379

  nats:
    image: nats:latest
    container_name: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - -p
      - "4222"
      - -m
      - "8222"
      - -js

  nats-test:
    image: nats:latest
    container_name: nats-test
    restart: unless-stopped
    ports:
      - "14222:4222"
      - "16222:6222"
      - "18222:8222"
    command:
      - -p
      - "4222"
      - -m
      - "8222"
      - -js

  issue-tracker-services-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: issue-tracker-services-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5555:80
    volumes:
      - ../data/pgadmin-data:/var/lib/pgadmin
