packages:
  - apps/**
  - packages/**
  - services/**
  - tools/**
allowBuilds:
  "@apollo/protobufjs": true
  "@apollo/rover": true
  "@firebase/util": true
  "@parcel/watcher": true
  "@swc/core": false
  argon2: true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true

minimumReleaseAge: 1440

overrides:
  typescript: "7.0.2"
  graphql: "16.14.2"
  uuid: "14.0.1"
