packages:
  - clients/**
  - packages/**
  - services/**
  - shared-ui/**
allowBuilds:
  '@apollo/protobufjs': true
  '@apollo/rover': true
  '@parcel/watcher': true
  '@swc/core': false
  argon2: true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  sharp: true

overrides:
  typescript: "npm:@typescript/native-preview@7.0.0-dev.20260707.2"
