packages:
  - apps/**
  - packages/**
  - services/**
  - shared-ui/**
allowBuilds:
  '@apollo/protobufjs': true
  '@apollo/rover': true
  '@parcel/watcher': true
  '@swc/core': false
  argon2: true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  sharp: true
  simple-git-hooks: true

overrides:
  typescript: "7.0.2"