federation_version: =2.8.1
subgraphs:
  checkout:
    routing_url: http://localhost:5000/graphql
    schema:
      file: ./services/auth/schema.graphql
  discovery:
    routing_url: http://localhost:5001/graphql
    schema:
      file: ./services/issue-tracker/schema.graphql