query FindItem($findItemId: String!) {
  findItem(id: $findItemId) {
    description
    id
    list {
      id
      name
    }
    parentItem {
      id
      name
    }
    subItems {
      id
      name
    }
    name
    priority
    status
  }
}
