query FindItem($findItemId: String!) {
  findItem(id: $findItemId) {
    id
    description
    list {
      id
      name
    }
    parentItem {
      id
      name
    }
    name
    priority
    statusId
  }
}
