query FindView($viewId: String!) {
  findView(viewId: $viewId) {
    id
    name
    type
    order
    list {
      id
      name
      selectedViewId
      space {
        id
        name
      }
    }
  }
}
