query FindViews($listId: String!) {
  findViews(listId: $listId) {
    id
    name
    type
    list {
      id
      name
      selectedViewId
      space {
        id
        name
      }
    }
  }
}
