// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, useMutation, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { createAttachment, loginWithEmailAndPassword, type Options } from '../sdk.gen';
import type { CreateAttachmentData, CreateAttachmentError, LoginWithEmailAndPasswordData, LoginWithEmailAndPasswordResponse } from '../types.gen';

/**
 * Login with email and password
 *
 * Authenticate a user with email and password via the identity provider
 */
export const loginWithEmailAndPasswordMutation = (options?: Partial<Options<LoginWithEmailAndPasswordData>>): UseMutationOptions<LoginWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<LoginWithEmailAndPasswordData>> => {
    const mutationOptions: UseMutationOptions<LoginWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<LoginWithEmailAndPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginWithEmailAndPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login with email and password
 *
 * Authenticate a user with email and password via the identity provider
 */
export const useLoginWithEmailAndPasswordMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<LoginWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<LoginWithEmailAndPasswordData>>, 'mutationFn'>>) => useMutation({ ...loginWithEmailAndPasswordMutation(), ...mutationOptions });

/**
 * Create a new issue attachment
 *
 * Create a new issue attachment
 */
export const createAttachmentMutation = (options?: Partial<Options<CreateAttachmentData>>): UseMutationOptions<unknown, AxiosError<CreateAttachmentError>, Options<CreateAttachmentData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CreateAttachmentError>, Options<CreateAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a new issue attachment
 *
 * Create a new issue attachment
 */
export const useCreateAttachmentMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<CreateAttachmentError>, Options<CreateAttachmentData>>, 'mutationFn'>>) => useMutation({ ...createAttachmentMutation(), ...mutationOptions });
