// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, useMutation, type UseMutationOptions, useQuery } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { acceptConsentChallenge, authorize, checkRelationship, createUploadTarget, deleteRelationship, ensureRelationship, exchangeToken, getAttachmentContent, getAttachmentVersionContent, getConsentChallenge, getCurrentUser, getIdentityFromAccessToken, getIdentityFromSession, listRelationships, logout, type Options, register, rejectConsentChallenge, resendVerificationEmail, signInWithEmailAndPassword, uploadToTarget, verifyEmail } from '../sdk.gen';
import type { AcceptConsentChallengeData, AcceptConsentChallengeResponse, AuthorizeData, CheckRelationshipData, CheckRelationshipResponse, CreateUploadTargetData, CreateUploadTargetResponse, DeleteRelationshipData, DeleteRelationshipResponse, EnsureRelationshipData, EnsureRelationshipResponse, ExchangeTokenData, ExchangeTokenResponse, GetAttachmentContentData, GetAttachmentVersionContentData, GetConsentChallengeData, GetConsentChallengeResponse, GetCurrentUserData, GetCurrentUserResponse, GetIdentityFromAccessTokenData, GetIdentityFromAccessTokenResponse, GetIdentityFromSessionData, GetIdentityFromSessionResponse, ListRelationshipsData, ListRelationshipsResponse, LogoutData, LogoutResponse, RegisterData, RegisterResponse, RejectConsentChallengeData, RejectConsentChallengeResponse, ResendVerificationEmailData, ResendVerificationEmailResponse, SignInWithEmailAndPasswordData, SignInWithEmailAndPasswordResponse, UploadToTargetData, UploadToTargetResponse, VerifyEmailData, VerifyEmailResponse } from '../types.gen';

/**
 * Sign in with email and password
 *
 * Authenticate a user with email and password via the identity provider. Sets the session cookie. When a login_challenge is present, returns redirectTo for the OAuth provider.
 */
export const signInWithEmailAndPasswordMutation = (options?: Partial<Options<SignInWithEmailAndPasswordData>>): UseMutationOptions<SignInWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<SignInWithEmailAndPasswordData>> => {
    const mutationOptions: UseMutationOptions<SignInWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<SignInWithEmailAndPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signInWithEmailAndPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign in with email and password
 *
 * Authenticate a user with email and password via the identity provider. Sets the session cookie. When a login_challenge is present, returns redirectTo for the OAuth provider.
 */
export const useSignInWithEmailAndPasswordMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<SignInWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<SignInWithEmailAndPasswordData>>, 'mutationFn'>>) => useMutation({ ...signInWithEmailAndPasswordMutation(), ...mutationOptions });

/**
 * Logout
 *
 * Invalidate the current session and clear the session cookie
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 *
 * Invalidate the current session and clear the session cookie
 */
export const useLogoutMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>>, 'mutationFn'>>) => useMutation({ ...logoutMutation(), ...mutationOptions });

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

/**
 * Get current authenticated user
 *
 * Return basic information about the current user by verifying the session cookie
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, AxiosError<DefaultError>, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

/**
 * Get current authenticated user
 *
 * Return basic information about the current user by verifying the session cookie
 */
export const useGetCurrentUserQuery = (options?: Options<GetCurrentUserData>) => useQuery(getCurrentUserOptions(options));

export const getIdentityFromSessionQueryKey = (options?: Options<GetIdentityFromSessionData>) => createQueryKey('getIdentityFromSession', options);

/**
 * Resolve session identity
 *
 * Verify the session cookie against Ory Kratos (SDK FrontendApi.toSession) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const getIdentityFromSessionOptions = (options?: Options<GetIdentityFromSessionData>) => queryOptions<GetIdentityFromSessionResponse, AxiosError<DefaultError>, GetIdentityFromSessionResponse, ReturnType<typeof getIdentityFromSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityFromSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityFromSessionQueryKey(options)
});

/**
 * Resolve session identity
 *
 * Verify the session cookie against Ory Kratos (SDK FrontendApi.toSession) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const useGetIdentityFromSessionQuery = (options?: Options<GetIdentityFromSessionData>) => useQuery(getIdentityFromSessionOptions(options));

export const getIdentityFromAccessTokenQueryKey = (options?: Options<GetIdentityFromAccessTokenData>) => createQueryKey('getIdentityFromAccessToken', options);

/**
 * Resolve identity from OAuth access token
 *
 * Introspect an OAuth provider access token (Authorization: Bearer) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const getIdentityFromAccessTokenOptions = (options?: Options<GetIdentityFromAccessTokenData>) => queryOptions<GetIdentityFromAccessTokenResponse, AxiosError<DefaultError>, GetIdentityFromAccessTokenResponse, ReturnType<typeof getIdentityFromAccessTokenQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityFromAccessToken({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityFromAccessTokenQueryKey(options)
});

/**
 * Resolve identity from OAuth access token
 *
 * Introspect an OAuth provider access token (Authorization: Bearer) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const useGetIdentityFromAccessTokenQuery = (options?: Options<GetIdentityFromAccessTokenData>) => useQuery(getIdentityFromAccessTokenOptions(options));

export const authorizeQueryKey = (options: Options<AuthorizeData>) => createQueryKey('authorize', options);

/**
 * OAuth authorize
 *
 * Start the OAuth authorization code flow. Redirects (302) to the OAuth provider authorization endpoint.
 */
export const authorizeOptions = (options: Options<AuthorizeData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof authorizeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authorize({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authorizeQueryKey(options)
});

/**
 * OAuth authorize
 *
 * Start the OAuth authorization code flow. Redirects (302) to the OAuth provider authorization endpoint.
 */
export const useAuthorizeQuery = (options: Options<AuthorizeData>) => useQuery(authorizeOptions(options));

export const getConsentChallengeQueryKey = (options: Options<GetConsentChallengeData>) => createQueryKey('getConsentChallenge', options);

/**
 * OAuth consent challenge
 *
 * Load OAuth consent challenge details by consent_challenge
 */
export const getConsentChallengeOptions = (options: Options<GetConsentChallengeData>) => queryOptions<GetConsentChallengeResponse, AxiosError<DefaultError>, GetConsentChallengeResponse, ReturnType<typeof getConsentChallengeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConsentChallenge({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConsentChallengeQueryKey(options)
});

/**
 * OAuth consent challenge
 *
 * Load OAuth consent challenge details by consent_challenge
 */
export const useGetConsentChallengeQuery = (options: Options<GetConsentChallengeData>) => useQuery(getConsentChallengeOptions(options));

/**
 * Accept OAuth consent
 *
 * Accept an OAuth consent challenge with granted scopes
 */
export const acceptConsentChallengeMutation = (options?: Partial<Options<AcceptConsentChallengeData>>): UseMutationOptions<AcceptConsentChallengeResponse, AxiosError<DefaultError>, Options<AcceptConsentChallengeData>> => {
    const mutationOptions: UseMutationOptions<AcceptConsentChallengeResponse, AxiosError<DefaultError>, Options<AcceptConsentChallengeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await acceptConsentChallenge({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Accept OAuth consent
 *
 * Accept an OAuth consent challenge with granted scopes
 */
export const useAcceptConsentChallengeMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<AcceptConsentChallengeResponse, AxiosError<DefaultError>, Options<AcceptConsentChallengeData>>, 'mutationFn'>>) => useMutation({ ...acceptConsentChallengeMutation(), ...mutationOptions });

/**
 * Reject OAuth consent
 *
 * Reject an OAuth consent challenge when the user denies access
 */
export const rejectConsentChallengeMutation = (options?: Partial<Options<RejectConsentChallengeData>>): UseMutationOptions<RejectConsentChallengeResponse, AxiosError<DefaultError>, Options<RejectConsentChallengeData>> => {
    const mutationOptions: UseMutationOptions<RejectConsentChallengeResponse, AxiosError<DefaultError>, Options<RejectConsentChallengeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await rejectConsentChallenge({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reject OAuth consent
 *
 * Reject an OAuth consent challenge when the user denies access
 */
export const useRejectConsentChallengeMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<RejectConsentChallengeResponse, AxiosError<DefaultError>, Options<RejectConsentChallengeData>>, 'mutationFn'>>) => useMutation({ ...rejectConsentChallengeMutation(), ...mutationOptions });

/**
 * OAuth token
 *
 * Exchange an authorization code for access (and optional refresh/id) tokens and set them as HTTP-only cookies
 */
export const exchangeTokenMutation = (options?: Partial<Options<ExchangeTokenData>>): UseMutationOptions<ExchangeTokenResponse, AxiosError<DefaultError>, Options<ExchangeTokenData>> => {
    const mutationOptions: UseMutationOptions<ExchangeTokenResponse, AxiosError<DefaultError>, Options<ExchangeTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await exchangeToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * OAuth token
 *
 * Exchange an authorization code for access (and optional refresh/id) tokens and set them as HTTP-only cookies
 */
export const useExchangeTokenMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<ExchangeTokenResponse, AxiosError<DefaultError>, Options<ExchangeTokenData>>, 'mutationFn'>>) => useMutation({ ...exchangeTokenMutation(), ...mutationOptions });

/**
 * Register
 *
 * Register a new user with email and password via the identity provider
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, AxiosError<DefaultError>, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, AxiosError<DefaultError>, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register
 *
 * Register a new user with email and password via the identity provider
 */
export const useRegisterMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<RegisterResponse, AxiosError<DefaultError>, Options<RegisterData>>, 'mutationFn'>>) => useMutation({ ...registerMutation(), ...mutationOptions });

export const verifyEmailQueryKey = (options: Options<VerifyEmailData>) => createQueryKey('verifyEmail', options);

/**
 * Verify email with Kratos code
 *
 * Complete email verification using the one-time code from the Kratos verification email
 */
export const verifyEmailOptions = (options: Options<VerifyEmailData>) => queryOptions<VerifyEmailResponse, AxiosError<DefaultError>, VerifyEmailResponse, ReturnType<typeof verifyEmailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await verifyEmail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: verifyEmailQueryKey(options)
});

/**
 * Verify email with Kratos code
 *
 * Complete email verification using the one-time code from the Kratos verification email
 */
export const useVerifyEmailQuery = (options: Options<VerifyEmailData>) => useQuery(verifyEmailOptions(options));

/**
 * Resend verification email
 *
 * Request a new email verification code. Always returns success to avoid revealing whether the email is registered.
 */
export const resendVerificationEmailMutation = (options?: Partial<Options<ResendVerificationEmailData>>): UseMutationOptions<ResendVerificationEmailResponse, AxiosError<DefaultError>, Options<ResendVerificationEmailData>> => {
    const mutationOptions: UseMutationOptions<ResendVerificationEmailResponse, AxiosError<DefaultError>, Options<ResendVerificationEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await resendVerificationEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Resend verification email
 *
 * Request a new email verification code. Always returns success to avoid revealing whether the email is registered.
 */
export const useResendVerificationEmailMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<ResendVerificationEmailResponse, AxiosError<DefaultError>, Options<ResendVerificationEmailData>>, 'mutationFn'>>) => useMutation({ ...resendVerificationEmailMutation(), ...mutationOptions });

export const getAttachmentContentQueryKey = (options: Options<GetAttachmentContentData>) => createQueryKey('getAttachmentContent', options);

/**
 * Get attachment content stream
 *
 * Download raw current version content for an attachment
 */
export const getAttachmentContentOptions = (options: Options<GetAttachmentContentData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getAttachmentContentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAttachmentContent({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAttachmentContentQueryKey(options)
});

/**
 * Get attachment content stream
 *
 * Download raw current version content for an attachment
 */
export const useGetAttachmentContentQuery = (options: Options<GetAttachmentContentData>) => useQuery(getAttachmentContentOptions(options));

export const getAttachmentVersionContentQueryKey = (options: Options<GetAttachmentVersionContentData>) => createQueryKey('getAttachmentVersionContent', options);

/**
 * Get attachment version content stream
 *
 * Download raw attachment version content
 */
export const getAttachmentVersionContentOptions = (options: Options<GetAttachmentVersionContentData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getAttachmentVersionContentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAttachmentVersionContent({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAttachmentVersionContentQueryKey(options)
});

/**
 * Get attachment version content stream
 *
 * Download raw attachment version content
 */
export const useGetAttachmentVersionContentQuery = (options: Options<GetAttachmentVersionContentData>) => useQuery(getAttachmentVersionContentOptions(options));

/**
 * Create upload target
 *
 * Create an upload target for uploading attachment files
 */
export const createUploadTargetMutation = (options?: Partial<Options<CreateUploadTargetData>>): UseMutationOptions<CreateUploadTargetResponse, AxiosError<DefaultError>, Options<CreateUploadTargetData>> => {
    const mutationOptions: UseMutationOptions<CreateUploadTargetResponse, AxiosError<DefaultError>, Options<CreateUploadTargetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUploadTarget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create upload target
 *
 * Create an upload target for uploading attachment files
 */
export const useCreateUploadTargetMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<CreateUploadTargetResponse, AxiosError<DefaultError>, Options<CreateUploadTargetData>>, 'mutationFn'>>) => useMutation({ ...createUploadTargetMutation(), ...mutationOptions });

/**
 * Upload file to upload target
 *
 * Upload file to upload target
 */
export const uploadToTargetMutation = (options?: Partial<Options<UploadToTargetData>>): UseMutationOptions<UploadToTargetResponse, AxiosError<DefaultError>, Options<UploadToTargetData>> => {
    const mutationOptions: UseMutationOptions<UploadToTargetResponse, AxiosError<DefaultError>, Options<UploadToTargetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadToTarget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload file to upload target
 *
 * Upload file to upload target
 */
export const useUploadToTargetMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<UploadToTargetResponse, AxiosError<DefaultError>, Options<UploadToTargetData>>, 'mutationFn'>>) => useMutation({ ...uploadToTargetMutation(), ...mutationOptions });

/**
 * Check a graph relationship
 *
 * Check a Keto permission: namespace, object, relation, and subject (subject_id, e.g. identity:<id>).
 */
export const checkRelationshipMutation = (options?: Partial<Options<CheckRelationshipData>>): UseMutationOptions<CheckRelationshipResponse, AxiosError<DefaultError>, Options<CheckRelationshipData>> => {
    const mutationOptions: UseMutationOptions<CheckRelationshipResponse, AxiosError<DefaultError>, Options<CheckRelationshipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await checkRelationship({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Check a graph relationship
 *
 * Check a Keto permission: namespace, object, relation, and subject (subject_id, e.g. identity:<id>).
 */
export const useCheckRelationshipMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<CheckRelationshipResponse, AxiosError<DefaultError>, Options<CheckRelationshipData>>, 'mutationFn'>>) => useMutation({ ...checkRelationshipMutation(), ...mutationOptions });

/**
 * Ensure a graph relationship exists
 *
 * Idempotently create a relationship in the authorization graph (Ory Keto). Used by domain services to grant permissions and role members.
 */
export const ensureRelationshipMutation = (options?: Partial<Options<EnsureRelationshipData>>): UseMutationOptions<EnsureRelationshipResponse, AxiosError<DefaultError>, Options<EnsureRelationshipData>> => {
    const mutationOptions: UseMutationOptions<EnsureRelationshipResponse, AxiosError<DefaultError>, Options<EnsureRelationshipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ensureRelationship({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Ensure a graph relationship exists
 *
 * Idempotently create a relationship in the authorization graph (Ory Keto). Used by domain services to grant permissions and role members.
 */
export const useEnsureRelationshipMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<EnsureRelationshipResponse, AxiosError<DefaultError>, Options<EnsureRelationshipData>>, 'mutationFn'>>) => useMutation({ ...ensureRelationshipMutation(), ...mutationOptions });

/**
 * Delete a graph relationship
 *
 * Idempotently delete a relationship from the authorization graph (Ory Keto).
 */
export const deleteRelationshipMutation = (options?: Partial<Options<DeleteRelationshipData>>): UseMutationOptions<DeleteRelationshipResponse, AxiosError<DefaultError>, Options<DeleteRelationshipData>> => {
    const mutationOptions: UseMutationOptions<DeleteRelationshipResponse, AxiosError<DefaultError>, Options<DeleteRelationshipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRelationship({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a graph relationship
 *
 * Idempotently delete a relationship from the authorization graph (Ory Keto).
 */
export const useDeleteRelationshipMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<DeleteRelationshipResponse, AxiosError<DefaultError>, Options<DeleteRelationshipData>>, 'mutationFn'>>) => useMutation({ ...deleteRelationshipMutation(), ...mutationOptions });

/**
 * List graph relationships
 *
 * List stored relationships for an object in the authorization graph.
 */
export const listRelationshipsMutation = (options?: Partial<Options<ListRelationshipsData>>): UseMutationOptions<ListRelationshipsResponse, AxiosError<DefaultError>, Options<ListRelationshipsData>> => {
    const mutationOptions: UseMutationOptions<ListRelationshipsResponse, AxiosError<DefaultError>, Options<ListRelationshipsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await listRelationships({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * List graph relationships
 *
 * List stored relationships for an object in the authorization graph.
 */
export const useListRelationshipsMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<ListRelationshipsResponse, AxiosError<DefaultError>, Options<ListRelationshipsData>>, 'mutationFn'>>) => useMutation({ ...listRelationshipsMutation(), ...mutationOptions });
