serve:
  cookies:
    same_site_mode: Lax
  public:
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:3001
        - http://localhost:5173
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type

urls:
  self:
    issuer: http://localhost:4444
  consent: http://localhost:3000/consent
  login: http://localhost:3000/signin
  logout: http://localhost:3000/logout
  device:
    verification: http://localhost:3000/device/verify
    success: http://localhost:3000/device/success

secrets:
  system:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

log:
  level: debug
  format: text
  leak_sensitive_values: true

strategies:
  access_token: jwt
  scope: exact
