/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as CallbackRouteImport } from './../routes/callback'
import { Route as AuthenticatedRouteImport } from './../routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './../routes/_authenticated/index'
import { Route as AuthenticatedMeRouteImport } from './../routes/_authenticated/me'
import { Route as AuthenticatedInventoryRouteImport } from './../routes/_authenticated/inventory'
import { Route as AuthenticatedHomeRouteImport } from './../routes/_authenticated/home'
import { Route as AuthenticatedCatalogRouteImport } from './../routes/_authenticated/catalog'
import { Route as noAuthEmailVerificationRouteImport } from './../routes/(no-auth)/email-verification'
import { Route as AuthenticatedIIssueIdRouteImport } from './../routes/_authenticated/i.$issueId'
import { Route as AuthenticatedVLViewIdRouteImport } from './../routes/_authenticated/v.l.$viewId'
import { Route as AuthenticatedVBViewIdRouteImport } from './../routes/_authenticated/v.b.$viewId'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const noAuthEmailVerificationRoute = noAuthEmailVerificationRouteImport.update({
  id: '/(no-auth)/email-verification',
  path: '/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIIssueIdRoute = AuthenticatedIIssueIdRouteImport.update({
  id: '/i/$issueId',
  path: '/i/$issueId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVLViewIdRoute = AuthenticatedVLViewIdRouteImport.update({
  id: '/v/l/$viewId',
  path: '/v/l/$viewId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVBViewIdRoute = AuthenticatedVBViewIdRouteImport.update({
  id: '/v/b/$viewId',
  path: '/v/b/$viewId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/email-verification': typeof noAuthEmailVerificationRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/me': typeof AuthenticatedMeRoute
  '/i/$issueId': typeof AuthenticatedIIssueIdRoute
  '/v/b/$viewId': typeof AuthenticatedVBViewIdRoute
  '/v/l/$viewId': typeof AuthenticatedVLViewIdRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/email-verification': typeof noAuthEmailVerificationRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/me': typeof AuthenticatedMeRoute
  '/': typeof AuthenticatedIndexRoute
  '/i/$issueId': typeof AuthenticatedIIssueIdRoute
  '/v/b/$viewId': typeof AuthenticatedVBViewIdRoute
  '/v/l/$viewId': typeof AuthenticatedVLViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/(no-auth)/email-verification': typeof noAuthEmailVerificationRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/i/$issueId': typeof AuthenticatedIIssueIdRoute
  '/_authenticated/v/b/$viewId': typeof AuthenticatedVBViewIdRoute
  '/_authenticated/v/l/$viewId': typeof AuthenticatedVLViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/email-verification'
    | '/catalog'
    | '/home'
    | '/inventory'
    | '/me'
    | '/i/$issueId'
    | '/v/b/$viewId'
    | '/v/l/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/email-verification'
    | '/catalog'
    | '/home'
    | '/inventory'
    | '/me'
    | '/'
    | '/i/$issueId'
    | '/v/b/$viewId'
    | '/v/l/$viewId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/(no-auth)/email-verification'
    | '/_authenticated/catalog'
    | '/_authenticated/home'
    | '/_authenticated/inventory'
    | '/_authenticated/me'
    | '/_authenticated/'
    | '/_authenticated/i/$issueId'
    | '/_authenticated/v/b/$viewId'
    | '/_authenticated/v/l/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  noAuthEmailVerificationRoute: typeof noAuthEmailVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(no-auth)/email-verification': {
      id: '/(no-auth)/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof noAuthEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/i/$issueId': {
      id: '/_authenticated/i/$issueId'
      path: '/i/$issueId'
      fullPath: '/i/$issueId'
      preLoaderRoute: typeof AuthenticatedIIssueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/v/l/$viewId': {
      id: '/_authenticated/v/l/$viewId'
      path: '/v/l/$viewId'
      fullPath: '/v/l/$viewId'
      preLoaderRoute: typeof AuthenticatedVLViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/v/b/$viewId': {
      id: '/_authenticated/v/b/$viewId'
      path: '/v/b/$viewId'
      fullPath: '/v/b/$viewId'
      preLoaderRoute: typeof AuthenticatedVBViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIIssueIdRoute: typeof AuthenticatedIIssueIdRoute
  AuthenticatedVBViewIdRoute: typeof AuthenticatedVBViewIdRoute
  AuthenticatedVLViewIdRoute: typeof AuthenticatedVLViewIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIIssueIdRoute: AuthenticatedIIssueIdRoute,
  AuthenticatedVBViewIdRoute: AuthenticatedVBViewIdRoute,
  AuthenticatedVLViewIdRoute: AuthenticatedVLViewIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  noAuthEmailVerificationRoute: noAuthEmailVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
