/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as CallbackRouteImport } from './../routes/callback'
import { Route as AuthenticatedRouteImport } from './../routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './../routes/_authenticated/index'
import { Route as AuthenticatedMeRouteImport } from './../routes/_authenticated/me'
import { Route as AuthenticatedInventoryRouteImport } from './../routes/_authenticated/inventory'
import { Route as noAuthEmailVerificationRouteImport } from './../routes/(no-auth)/email-verification'
import { Route as AuthenticatedWorkspacesIdRouteImport } from './../routes/_authenticated/workspaces.$id'
import { Route as AuthenticatedIIssueIdRouteImport } from './../routes/_authenticated/i.$issueId'
import { Route as AuthenticatedWorkspaceIdHomeRouteImport } from './../routes/_authenticated/$workspaceId.home'
import { Route as AuthenticatedWorkspacesIdSettingsRouteImport } from './../routes/_authenticated/workspaces.$id.settings'
import { Route as AuthenticatedWorkspacesIdMembersRouteImport } from './../routes/_authenticated/workspaces.$id.members'
import { Route as AuthenticatedWorkspaceIdVLViewIdRouteImport } from './../routes/_authenticated/$workspaceId.v.l.$viewId'
import { Route as AuthenticatedWorkspaceIdVBViewIdRouteImport } from './../routes/_authenticated/$workspaceId.v.b.$viewId'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const noAuthEmailVerificationRoute = noAuthEmailVerificationRouteImport.update({
  id: '/(no-auth)/email-verification',
  path: '/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesIdRoute =
  AuthenticatedWorkspacesIdRouteImport.update({
    id: '/workspaces/$id',
    path: '/workspaces/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIIssueIdRoute = AuthenticatedIIssueIdRouteImport.update({
  id: '/i/$issueId',
  path: '/i/$issueId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceIdHomeRoute =
  AuthenticatedWorkspaceIdHomeRouteImport.update({
    id: '/$workspaceId/home',
    path: '/$workspaceId/home',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIdSettingsRoute =
  AuthenticatedWorkspacesIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any)
const AuthenticatedWorkspacesIdMembersRoute =
  AuthenticatedWorkspacesIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesIdRoute,
  } as any)
const AuthenticatedWorkspaceIdVLViewIdRoute =
  AuthenticatedWorkspaceIdVLViewIdRouteImport.update({
    id: '/$workspaceId/v/l/$viewId',
    path: '/$workspaceId/v/l/$viewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceIdVBViewIdRoute =
  AuthenticatedWorkspaceIdVBViewIdRouteImport.update({
    id: '/$workspaceId/v/b/$viewId',
    path: '/$workspaceId/v/b/$viewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/email-verification': typeof noAuthEmailVerificationRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/me': typeof AuthenticatedMeRoute
  '/$workspaceId/home': typeof AuthenticatedWorkspaceIdHomeRoute
  '/i/$issueId': typeof AuthenticatedIIssueIdRoute
  '/workspaces/$id': typeof AuthenticatedWorkspacesIdRouteWithChildren
  '/workspaces/$id/members': typeof AuthenticatedWorkspacesIdMembersRoute
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRoute
  '/$workspaceId/v/b/$viewId': typeof AuthenticatedWorkspaceIdVBViewIdRoute
  '/$workspaceId/v/l/$viewId': typeof AuthenticatedWorkspaceIdVLViewIdRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/email-verification': typeof noAuthEmailVerificationRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/me': typeof AuthenticatedMeRoute
  '/': typeof AuthenticatedIndexRoute
  '/$workspaceId/home': typeof AuthenticatedWorkspaceIdHomeRoute
  '/i/$issueId': typeof AuthenticatedIIssueIdRoute
  '/workspaces/$id': typeof AuthenticatedWorkspacesIdRouteWithChildren
  '/workspaces/$id/members': typeof AuthenticatedWorkspacesIdMembersRoute
  '/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRoute
  '/$workspaceId/v/b/$viewId': typeof AuthenticatedWorkspaceIdVBViewIdRoute
  '/$workspaceId/v/l/$viewId': typeof AuthenticatedWorkspaceIdVLViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/(no-auth)/email-verification': typeof noAuthEmailVerificationRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$workspaceId/home': typeof AuthenticatedWorkspaceIdHomeRoute
  '/_authenticated/i/$issueId': typeof AuthenticatedIIssueIdRoute
  '/_authenticated/workspaces/$id': typeof AuthenticatedWorkspacesIdRouteWithChildren
  '/_authenticated/workspaces/$id/members': typeof AuthenticatedWorkspacesIdMembersRoute
  '/_authenticated/workspaces/$id/settings': typeof AuthenticatedWorkspacesIdSettingsRoute
  '/_authenticated/$workspaceId/v/b/$viewId': typeof AuthenticatedWorkspaceIdVBViewIdRoute
  '/_authenticated/$workspaceId/v/l/$viewId': typeof AuthenticatedWorkspaceIdVLViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/email-verification'
    | '/inventory'
    | '/me'
    | '/$workspaceId/home'
    | '/i/$issueId'
    | '/workspaces/$id'
    | '/workspaces/$id/members'
    | '/workspaces/$id/settings'
    | '/$workspaceId/v/b/$viewId'
    | '/$workspaceId/v/l/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/email-verification'
    | '/inventory'
    | '/me'
    | '/'
    | '/$workspaceId/home'
    | '/i/$issueId'
    | '/workspaces/$id'
    | '/workspaces/$id/members'
    | '/workspaces/$id/settings'
    | '/$workspaceId/v/b/$viewId'
    | '/$workspaceId/v/l/$viewId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/(no-auth)/email-verification'
    | '/_authenticated/inventory'
    | '/_authenticated/me'
    | '/_authenticated/'
    | '/_authenticated/$workspaceId/home'
    | '/_authenticated/i/$issueId'
    | '/_authenticated/workspaces/$id'
    | '/_authenticated/workspaces/$id/members'
    | '/_authenticated/workspaces/$id/settings'
    | '/_authenticated/$workspaceId/v/b/$viewId'
    | '/_authenticated/$workspaceId/v/l/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  noAuthEmailVerificationRoute: typeof noAuthEmailVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(no-auth)/email-verification': {
      id: '/(no-auth)/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof noAuthEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces/$id': {
      id: '/_authenticated/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/i/$issueId': {
      id: '/_authenticated/i/$issueId'
      path: '/i/$issueId'
      fullPath: '/i/$issueId'
      preLoaderRoute: typeof AuthenticatedIIssueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$workspaceId/home': {
      id: '/_authenticated/$workspaceId/home'
      path: '/$workspaceId/home'
      fullPath: '/$workspaceId/home'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$id/settings': {
      id: '/_authenticated/workspaces/$id/settings'
      path: '/settings'
      fullPath: '/workspaces/$id/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdRoute
    }
    '/_authenticated/workspaces/$id/members': {
      id: '/_authenticated/workspaces/$id/members'
      path: '/members'
      fullPath: '/workspaces/$id/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesIdMembersRouteImport
      parentRoute: typeof AuthenticatedWorkspacesIdRoute
    }
    '/_authenticated/$workspaceId/v/l/$viewId': {
      id: '/_authenticated/$workspaceId/v/l/$viewId'
      path: '/$workspaceId/v/l/$viewId'
      fullPath: '/$workspaceId/v/l/$viewId'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdVLViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$workspaceId/v/b/$viewId': {
      id: '/_authenticated/$workspaceId/v/b/$viewId'
      path: '/$workspaceId/v/b/$viewId'
      fullPath: '/$workspaceId/v/b/$viewId'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdVBViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedWorkspacesIdRouteChildren {
  AuthenticatedWorkspacesIdMembersRoute: typeof AuthenticatedWorkspacesIdMembersRoute
  AuthenticatedWorkspacesIdSettingsRoute: typeof AuthenticatedWorkspacesIdSettingsRoute
}

const AuthenticatedWorkspacesIdRouteChildren: AuthenticatedWorkspacesIdRouteChildren =
  {
    AuthenticatedWorkspacesIdMembersRoute:
      AuthenticatedWorkspacesIdMembersRoute,
    AuthenticatedWorkspacesIdSettingsRoute:
      AuthenticatedWorkspacesIdSettingsRoute,
  }

const AuthenticatedWorkspacesIdRouteWithChildren =
  AuthenticatedWorkspacesIdRoute._addFileChildren(
    AuthenticatedWorkspacesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkspaceIdHomeRoute: typeof AuthenticatedWorkspaceIdHomeRoute
  AuthenticatedIIssueIdRoute: typeof AuthenticatedIIssueIdRoute
  AuthenticatedWorkspacesIdRoute: typeof AuthenticatedWorkspacesIdRouteWithChildren
  AuthenticatedWorkspaceIdVBViewIdRoute: typeof AuthenticatedWorkspaceIdVBViewIdRoute
  AuthenticatedWorkspaceIdVLViewIdRoute: typeof AuthenticatedWorkspaceIdVLViewIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkspaceIdHomeRoute: AuthenticatedWorkspaceIdHomeRoute,
  AuthenticatedIIssueIdRoute: AuthenticatedIIssueIdRoute,
  AuthenticatedWorkspacesIdRoute: AuthenticatedWorkspacesIdRouteWithChildren,
  AuthenticatedWorkspaceIdVBViewIdRoute: AuthenticatedWorkspaceIdVBViewIdRoute,
  AuthenticatedWorkspaceIdVLViewIdRoute: AuthenticatedWorkspaceIdVLViewIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  noAuthEmailVerificationRoute: noAuthEmailVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
