DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  id UUID DEFAULT uuid_generate_v4() NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_email_verified BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,

  PRIMARY KEY (id),
  CHECK (LENGTH(email) <= 80),
  CHECK (LENGTH(password) BETWEEN 8 AND 64)
);