schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
{
  query: Query
  mutation: Mutation
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

type Attachment
  @join__type(graph: ATTACHMENT)
{
  bucket: String!
  id: String!
  thumbnailLink: String!
}

input CreateIssueInput
  @join__type(graph: ISSUE_TRACKER)
{
  assigneeIds: [String!]!
  component: String
  description: String
  dueDate: DateTimeISO
  estimate: Int
  name: String!
  parentIssueId: String
  priority: String!
  projectId: String!
  statusId: ID!
  type: String!
}

input CreateProjectInput
  @join__type(graph: ISSUE_TRACKER)
{
  name: String!
  workspaceId: String!
}

input CreateWorkspaceInput
  @join__type(graph: ISSUE_TRACKER)
{
  description: String
  id: String
  name: String!
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.This scalar is serialized to a string in ISO 8601 format and parsed from a string in ISO 8601 format.
"""
scalar DateTimeISO
  @join__type(graph: IDENTITY_SERVICE)
  @join__type(graph: ISSUE_TRACKER)

input FindIssuesInput
  @join__type(graph: ISSUE_TRACKER)
{
  parentIssueId: String!
}

input FindProjectsOptions
  @join__type(graph: ISSUE_TRACKER)
{
  workspaceId: String
}

input FindStatusesOptions
  @join__type(graph: ISSUE_TRACKER)
{
  projectId: String!
}

type Issue
  @join__type(graph: ISSUE_TRACKER)
{
  component: String
  description: String
  estimate: Int
  id: String!
  name: String!
  parentIssue: Issue
  priority: String!
  project: Project!
  statusId: String!
  subIssues: [Issue!]
}

scalar join__FieldSet

enum join__Graph {
  ATTACHMENT @join__graph(name: "attachment", url: "http://127.0.0.1:4003/graphql")
  IDENTITY_SERVICE @join__graph(name: "identity-service", url: "http://127.0.0.1:4001/graphql")
  ISSUE_TRACKER @join__graph(name: "issue-tracker", url: "http://127.0.0.1:4002/graphql")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Mutation
  @join__type(graph: ATTACHMENT)
  @join__type(graph: IDENTITY_SERVICE)
  @join__type(graph: ISSUE_TRACKER)
{
  deleteAttachment(id: String!): String! @join__field(graph: ATTACHMENT)
  logout: String! @join__field(graph: IDENTITY_SERVICE)
  registerUser(input: RegisterUserInput!): String! @join__field(graph: IDENTITY_SERVICE)
  signInWithEmailAndPassword(input: SignInWithEmailAndPasswordInput!): Boolean! @join__field(graph: IDENTITY_SERVICE)
  verifyVerificationLink(input: VerifyVerificationLinkInput!): String! @join__field(graph: IDENTITY_SERVICE)
  createIssue(input: CreateIssueInput!): String! @join__field(graph: ISSUE_TRACKER)
  createProject(input: CreateProjectInput!): String! @join__field(graph: ISSUE_TRACKER)
  createWorkspace(input: CreateWorkspaceInput!): String! @join__field(graph: ISSUE_TRACKER)
  deleteIssue: String! @join__field(graph: ISSUE_TRACKER)
  updateIssue(input: UpdateIssueInput!): String! @join__field(graph: ISSUE_TRACKER)
}

type PaginatedAttachment
  @join__type(graph: ATTACHMENT)
{
  rowCount: Float!
  rows: [Attachment!]!
}

type PaginatedProject
  @join__type(graph: ISSUE_TRACKER)
{
  rowCount: Float!
  rows: [Project!]!
}

type Project
  @join__type(graph: ISSUE_TRACKER)
{
  id: String!
  name: String!
  workspace: Workspace!
  workspaceId: String!
}

type Query
  @join__type(graph: ATTACHMENT)
  @join__type(graph: IDENTITY_SERVICE)
  @join__type(graph: ISSUE_TRACKER)
{
  findAttachments(issueId: String!): PaginatedAttachment! @join__field(graph: ATTACHMENT)
  getCurrentUser: User @join__field(graph: IDENTITY_SERVICE)
  findDefaultWorkspace: Workspace! @join__field(graph: ISSUE_TRACKER)
  findIssue(id: String!): Issue @join__field(graph: ISSUE_TRACKER)
  findProject(id: String!): Project! @join__field(graph: ISSUE_TRACKER)
  findProjectIssues(projectId: String!): [Issue!]! @join__field(graph: ISSUE_TRACKER)
  findProjects(input: FindProjectsOptions): PaginatedProject! @join__field(graph: ISSUE_TRACKER)
  findStatuses(input: FindStatusesOptions!): [Status!]! @join__field(graph: ISSUE_TRACKER)
  findSubIssues(input: FindIssuesInput!): [Issue!]! @join__field(graph: ISSUE_TRACKER)
  findWorkspaces: [Workspace!]! @join__field(graph: ISSUE_TRACKER)
}

input RegisterUserInput
  @join__type(graph: IDENTITY_SERVICE)
{
  displayName: String!
  email: String!
  password: String!
}

input SignInWithEmailAndPasswordInput
  @join__type(graph: IDENTITY_SERVICE)
{
  email: String!
  password: String!
}

type Status
  @join__type(graph: ISSUE_TRACKER)
{
  id: String!
  name: String!
}

input UpdateIssueInput
  @join__type(graph: ISSUE_TRACKER)
{
  component: String
  description: String
  dueDate: DateTimeISO
  estimate: Int
  issueId: String!
  name: String
  priority: String
  statusId: String
  type: String
}

type User
  @join__type(graph: IDENTITY_SERVICE)
{
  createdAt: DateTimeISO!
  description: String
  displayName: String
  email: String!
  emailVerificationStatus: String!
  photoUrl: String
  userId: String!
}

input VerifyVerificationLinkInput
  @join__type(graph: IDENTITY_SERVICE)
{
  token: String!
}

type Workspace
  @join__type(graph: ISSUE_TRACKER)
{
  createdById: String!
  description: String
  id: String!
  name: String!
  status: String!
}
