schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
{
  query: Query
  mutation: Mutation
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

type Attachment
  @join__type(graph: ATTACHMENT)
{
  bucket: String!
  id: String!
  thumbnailLink: String!
}

input CreateItemInput
  @join__type(graph: ISSUE_TRACKER)
{
  assigneeIds: [String!]!
  description: String
  dueDate: DateTimeISO
  fields: JSON
  listId: String!
  name: String!
  parentItemId: String
  priority: String!
  statusId: ID!
  type: String!
}

input CreateListInput
  @join__type(graph: ISSUE_TRACKER)
{
  name: String!
  spaceId: String!
}

input CreateSpaceInput
  @join__type(graph: ISSUE_TRACKER)
{
  description: String
  name: String!
  workspaceId: String!
}

input CreateWorkspaceInput
  @join__type(graph: ISSUE_TRACKER)
{
  description: String
  id: String
  name: String!
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.This scalar is serialized to a string in ISO 8601 format and parsed from a string in ISO 8601 format.
"""
scalar DateTimeISO
  @join__type(graph: AUTH)
  @join__type(graph: ISSUE_TRACKER)

input FindCustomFieldsOptions
  @join__type(graph: ISSUE_TRACKER)
{
  listId: String!
}

input FindItemsInput
  @join__type(graph: ISSUE_TRACKER)
{
  parentItemId: String!
}

input FindSpacesOptions
  @join__type(graph: ISSUE_TRACKER)
{
  workspaceId: String!
}

input FindStatusesOptions
  @join__type(graph: ISSUE_TRACKER)
{
  listId: String!
}

type Item
  @join__type(graph: ISSUE_TRACKER)
{
  description: String
  id: String!
  list: List!
  name: String!
  parentItem: Item
  priority: String!
  statusId: String!
  subItems: [Item!]
}

scalar join__FieldSet

enum join__Graph {
  ATTACHMENT @join__graph(name: "attachment", url: "http://localhost:5002/api/graphql")
  AUTH @join__graph(name: "auth", url: "http://localhost:5000/api/graphql")
  ISSUE_TRACKER @join__graph(name: "issue-tracker", url: "http://localhost:5001/api/graphql")
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON
  @join__type(graph: ISSUE_TRACKER)

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type List
  @join__type(graph: ISSUE_TRACKER)
{
  id: String!
  name: String!
  selectedViewId: String
  space: Space!
}

type ListCustomField
  @join__type(graph: ISSUE_TRACKER)
{
  customFieldId: String!
  id: String!
  listId: String!
}

type Mutation
  @join__type(graph: ATTACHMENT)
  @join__type(graph: AUTH)
  @join__type(graph: ISSUE_TRACKER)
{
  deleteAttachment(id: String!): String! @join__field(graph: ATTACHMENT)
  logout: String! @join__field(graph: AUTH)
  registerUser(input: RegisterUserInput!): String! @join__field(graph: AUTH)
  signInWithEmailAndPassword(input: SignInWithEmailAndPasswordInput!): Boolean! @join__field(graph: AUTH)
  verifyVerificationLink(input: VerifyVerificationLinkInput!): String! @join__field(graph: AUTH)
  createItem(input: CreateItemInput!): String! @join__field(graph: ISSUE_TRACKER)
  createList(input: CreateListInput!): String! @join__field(graph: ISSUE_TRACKER)
  createSpace(input: CreateSpaceInput!): String! @join__field(graph: ISSUE_TRACKER)
  createWorkspace(input: CreateWorkspaceInput!): String! @join__field(graph: ISSUE_TRACKER)
  deleteItem: String! @join__field(graph: ISSUE_TRACKER)
  updateItem(input: UpdateItemInput!): String! @join__field(graph: ISSUE_TRACKER)
}

type PaginatedAttachment
  @join__type(graph: ATTACHMENT)
{
  rowCount: Float!
  rows: [Attachment!]!
}

type PaginatedList
  @join__type(graph: ISSUE_TRACKER)
{
  rowCount: Float!
  rows: [List!]!
}

type Query
  @join__type(graph: ATTACHMENT)
  @join__type(graph: AUTH)
  @join__type(graph: ISSUE_TRACKER)
{
  findAttachments(itemId: String!): PaginatedAttachment! @join__field(graph: ATTACHMENT)
  getCurrentUser: User! @join__field(graph: AUTH)
  findCustomFields(options: FindCustomFieldsOptions!): [ListCustomField!]! @join__field(graph: ISSUE_TRACKER)
  findDefaultWorkspace: Workspace! @join__field(graph: ISSUE_TRACKER)
  findItem(id: String!): Item @join__field(graph: ISSUE_TRACKER)
  findList(id: String!): List! @join__field(graph: ISSUE_TRACKER)
  findListItems(listId: String!): [Item!]! @join__field(graph: ISSUE_TRACKER)
  findLists: PaginatedList! @join__field(graph: ISSUE_TRACKER)
  findSpaces(input: FindSpacesOptions!): [Space!]! @join__field(graph: ISSUE_TRACKER)
  findStatuses(input: FindStatusesOptions!): [Status!]! @join__field(graph: ISSUE_TRACKER)
  findSubItems(input: FindItemsInput!): [Item!]! @join__field(graph: ISSUE_TRACKER)
  findView(viewId: String!): View! @join__field(graph: ISSUE_TRACKER)
  findViews(listId: String!): [View!]! @join__field(graph: ISSUE_TRACKER)
  findWorkspaces: [Workspace!]! @join__field(graph: ISSUE_TRACKER)
}

input RegisterUserInput
  @join__type(graph: AUTH)
{
  displayName: String!
  email: String!
  password: String!
}

input SignInWithEmailAndPasswordInput
  @join__type(graph: AUTH)
{
  email: String!
  password: String!
}

type Space
  @join__type(graph: ISSUE_TRACKER)
{
  id: String!
  lists: [List!]
  name: String!
}

type Status
  @join__type(graph: ISSUE_TRACKER)
{
  id: String!
  name: String!
}

input UpdateItemInput
  @join__type(graph: ISSUE_TRACKER)
{
  description: String
  dueDate: DateTimeISO
  itemId: String!
  name: String
  priority: String
  statusId: String
  type: String
}

type User
  @join__type(graph: AUTH)
{
  createdAt: DateTimeISO!
  description: String
  displayName: String
  email: String!
  emailVerificationStatus: String!
  photoUrl: String
  userId: String!
}

input VerifyVerificationLinkInput
  @join__type(graph: AUTH)
{
  token: String!
}

type View
  @join__type(graph: ISSUE_TRACKER)
{
  id: String!
  list: List!
  name: String!
  order: Float!
  type: String!
}

type Workspace
  @join__type(graph: ISSUE_TRACKER)
{
  createdById: String!
  description: String
  id: String!
  name: String!
  status: String!
}
