services:
  attachment-redis:
    image: redis:8.8.0
    container_name: attachment-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - 6380:6379

  nats:
    image: nats:2.14.3
    container_name: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - -p
      - "4222"
      - -m
      - "8222"
      - -js

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: pgadmin
    restart: unless-stopped
    entrypoint: /custom/docker-entrypoint.sh
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_REPLACE_SERVERS_ON_STARTUP=True
      - PGADMIN_SERVER_JSON_FILE=/var/lib/pgadmin/servers.json
      - PGPASS_FILE=/var/lib/pgadmin/pgpass
      - POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_AUTH_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_ISSUES_PASSWORD=${POSTGRES_ISSUES_PASSWORD}
      - POSTGRES_MAIL_PASSWORD=${POSTGRES_MAIL_PASSWORD}
      - POSTGRES_ATTACHMENT_PASSWORD=${POSTGRES_ATTACHMENT_PASSWORD}
    ports:
      - 5555:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/docker-entrypoint.sh:/custom/docker-entrypoint.sh:ro

  grafana:
    image: grafana/grafana:13.1.0
    container_name: grafana
    profiles: [ observability ]
    ports:
      - 3300:3000

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    profiles: [ observability ]
    volumes:
      - ./observability/loki.yaml:/etc/loki/loki.yaml:ro
      - ./data/loki-data:/loki
    command: -config.file=/etc/loki/loki.yaml

  tempo:
    image: grafana/tempo:3.0.2
    container_name: tempo
    profiles: [ observability ]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo.yaml:ro
      - ./data/tempo-data:/var/tempo
    command:
      - -config.file=/etc/tempo.yaml
      - -target=all

  prometheus:
    image: prom/prometheus:v3.13.1
    container_name: prometheus
    profiles: [ observability ]
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  alloy:
    image: grafana/alloy:v1.17.1
    container_name: alloy
    profiles: [ observability ]
