services:
  auth-postgres:
    image: postgres:18.4
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=auth
    volumes:
      - ./data/auth-postgres-data:/var/lib/postgresql
    command:
      - postgres
      - -c
      - max_connections=50

  issues-postgres:
    image: postgres:18.4
    container_name: issues-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=issues
      - POSTGRES_PASSWORD=${POSTGRES_ISSUES_PASSWORD}
      - POSTGRES_DB=issues
    volumes:
      - ./data/issues-postgres-data:/var/lib/postgresql
    command:
      - postgres
      - -c
      - max_connections=50

  mail-postgres:
    image: postgres:18.4
    container_name: mail-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mail
      - POSTGRES_PASSWORD=${POSTGRES_MAIL_PASSWORD}
      - POSTGRES_DB=mail
    volumes:
      - ./data/mail-postgres-data:/var/lib/postgresql
    command:
      - postgres
      - -c
      - max_connections=50

  attachment-postgres:
    image: postgres:18.4
    container_name: attachment-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=attachment
      - POSTGRES_PASSWORD=${POSTGRES_ATTACHMENT_PASSWORD}
      - POSTGRES_DB=attachment
    volumes:
      - ./data/attachment-postgres-data:/var/lib/postgresql
    command:
      - postgres
      - -c
      - max_connections=50

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    entrypoint: ["/pgadmin4/docker-entrypoint.sh"]
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_REPLACE_SERVERS_ON_STARTUP=True
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
      - PGADMIN_CONFIG_TYPE=multi-db
      - PGPASS_FILE=/config/pgpass
    ports:
      - 5555:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
      - ./pgadmin:/pgadmin4
      - ./pgadmin/pgpass:/config/pgpass
