services:
  postgres:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      # Admin role
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}

      # Service roles (order matches .env)
      - POSTGRES_IDENTITY_PASSWORD=${POSTGRES_IDENTITY_PASSWORD}
      - POSTGRES_ISSUES_PASSWORD=${POSTGRES_ISSUES_PASSWORD}
      - POSTGRES_INVENTORY_PASSWORD=${POSTGRES_INVENTORY_PASSWORD}
      - POSTGRES_ATTACHMENT_PASSWORD=${POSTGRES_ATTACHMENT_PASSWORD}
      - POSTGRES_NOTIFICATION_PASSWORD=${POSTGRES_NOTIFICATION_PASSWORD}
    volumes:
      - ../data/docker/pg-single-db-data:/var/lib/postgresql
      - ./init-db/single-db:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M
