services:
  attachment-redis:
    image: redis:8.0-M02-alpine
    container_name: attachment-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - 6380:6379

  nats:
    image: nats:latest
    container_name: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - -p
      - "4222"
      - -m
      - "8222"
      - -js

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    entrypoint: /custom/docker-entrypoint.sh
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_REPLACE_SERVERS_ON_STARTUP=True
      - PGADMIN_SERVER_JSON_FILE=/var/lib/pgadmin/servers.json
      - PGPASS_FILE=/var/lib/pgadmin/pgpass
      - POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_AUTH_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_ISSUES_PASSWORD=${POSTGRES_ISSUES_PASSWORD}
      - POSTGRES_MAIL_PASSWORD=${POSTGRES_MAIL_PASSWORD}
      - POSTGRES_ATTACHMENT_PASSWORD=${POSTGRES_ATTACHMENT_PASSWORD}
    ports:
      - 5555:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/docker-entrypoint.sh:/custom/docker-entrypoint.sh:ro
