services:
  kratos-migrate:
    image: oryd/kratos:v26.2.0
    environment:
      - DSN=postgresql://kratos:${POSTGRES_KRATOS_PASSWORD}@ory-postgres:5432/kratos?sslmode=disable
    volumes:
      - ./identity/kratos:/etc/config/kratos:ro
    command: migrate -c /etc/config/kratos/kratos.yaml sql -e --yes
    restart: on-failure
    depends_on:
      ory-postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 32M

  kratos:
    image: oryd/kratos:v26.2.0
    restart: unless-stopped
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    environment:
      - DSN=postgresql://kratos:${POSTGRES_KRATOS_PASSWORD}@ory-postgres:5432/kratos?sslmode=disable
      - LOG_LEVEL=debug
      - SECRETS_COOKIE=${KRATOS_SECRETS_COOKIE}
      - SECRETS_CIPHER=${KRATOS_SECRETS_CIPHER}
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      - ./identity/kratos:/etc/config/kratos:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 64M
