services:
  seaweedfs:
    image: chrislusf/seaweedfs:3.97
    restart: unless-stopped
    command:
      - server
      - -dir=/data
      - -ip.bind=0.0.0.0
      - -master.port=9333
      - -volume.port=8080
      - -filer
      - -s3
      - -s3.port=8333
    ports:
      - "8333:8333"
      - "8888:8888"
      - "9333:9333"
    volumes:
      - ../data/docker/seaweedfs-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M
