/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AuthenticatedRouteImport } from './../routes/_authenticated'
import { Route as CallbackRouteImport } from './../routes/callback'
import { Route as AuthenticatedIndexRouteImport } from './../routes/_authenticated/index'
import { Route as AuthenticatedRelationsRouteImport } from './../routes/_authenticated/relations'
import { Route as AuthenticatedTenantsRouteImport } from './../routes/_authenticated/tenants'
import { Route as AuthenticatedRelationsRoleIdRouteImport } from './../routes/_authenticated/relations_.$roleId'
import { Route as AuthenticatedTenantsTenantIdRouteImport } from './../routes/_authenticated/tenants_.$tenantId'
import { Route as AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRouteImport } from './../routes/_authenticated/tenants_.$tenantId_.organizations.$organizationId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelationsRoute = AuthenticatedRelationsRouteImport.update({
  id: '/relations',
  path: '/relations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelationsRoleIdRoute =
  AuthenticatedRelationsRoleIdRouteImport.update({
    id: '/relations_/$roleId',
    path: '/relations/$roleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdRoute =
  AuthenticatedTenantsTenantIdRouteImport.update({
    id: '/tenants_/$tenantId',
    path: '/tenants/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute =
  AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRouteImport.update({
    id: '/tenants_/$tenantId_/organizations/$organizationId',
    path: '/tenants/$tenantId/organizations/$organizationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/relations': typeof AuthenticatedRelationsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/relations/$roleId': typeof AuthenticatedRelationsRoleIdRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/$tenantId/organizations/$organizationId': typeof AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/relations': typeof AuthenticatedRelationsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/': typeof AuthenticatedIndexRoute
  '/relations/$roleId': typeof AuthenticatedRelationsRoleIdRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/$tenantId/organizations/$organizationId': typeof AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/relations': typeof AuthenticatedRelationsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/relations_/$roleId': typeof AuthenticatedRelationsRoleIdRoute
  '/_authenticated/tenants_/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/_authenticated/tenants_/$tenantId_/organizations/$organizationId': typeof AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/relations'
    | '/tenants'
    | '/relations/$roleId'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/organizations/$organizationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/relations'
    | '/tenants'
    | '/'
    | '/relations/$roleId'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/organizations/$organizationId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/relations'
    | '/_authenticated/tenants'
    | '/_authenticated/'
    | '/_authenticated/relations_/$roleId'
    | '/_authenticated/tenants_/$tenantId'
    | '/_authenticated/tenants_/$tenantId_/organizations/$organizationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relations': {
      id: '/_authenticated/relations'
      path: '/relations'
      fullPath: '/relations'
      preLoaderRoute: typeof AuthenticatedRelationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relations_/$roleId': {
      id: '/_authenticated/relations_/$roleId'
      path: '/relations/$roleId'
      fullPath: '/relations/$roleId'
      preLoaderRoute: typeof AuthenticatedRelationsRoleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants_/$tenantId': {
      id: '/_authenticated/tenants_/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants_/$tenantId_/organizations/$organizationId': {
      id: '/_authenticated/tenants_/$tenantId_/organizations/$organizationId'
      path: '/tenants/$tenantId/organizations/$organizationId'
      fullPath: '/tenants/$tenantId/organizations/$organizationId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedRelationsRoute: typeof AuthenticatedRelationsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRelationsRoleIdRoute: typeof AuthenticatedRelationsRoleIdRoute
  AuthenticatedTenantsTenantIdRoute: typeof AuthenticatedTenantsTenantIdRoute
  AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute: typeof AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRelationsRoute: AuthenticatedRelationsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRelationsRoleIdRoute: AuthenticatedRelationsRoleIdRoute,
  AuthenticatedTenantsTenantIdRoute: AuthenticatedTenantsTenantIdRoute,
  AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute:
    AuthenticatedTenantsTenantIdOrganizationsOrganizationIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
