// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, useMutation, type UseMutationOptions, useQuery } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { adminDeleteUser, authorize, createAttachment, getCurrentUser, loginWithEmailAndPassword, logout, type Options, registerWithEmailAndPassword } from '../sdk.gen';
import type { AdminDeleteUserData, AdminDeleteUserResponse, AuthorizeData, AuthorizeResponse, CreateAttachmentData, CreateAttachmentError, GetCurrentUserData, GetCurrentUserResponse, LoginWithEmailAndPasswordData, LoginWithEmailAndPasswordResponse, LogoutData, LogoutResponse, RegisterWithEmailAndPasswordData, RegisterWithEmailAndPasswordResponse } from '../types.gen';

/**
 * Delete user
 *
 * Admin endpoint: soft-delete the local user (and profile) and permanently delete the identity from the identity provider
 */
export const adminDeleteUserMutation = (options?: Partial<Options<AdminDeleteUserData>>): UseMutationOptions<AdminDeleteUserResponse, AxiosError<DefaultError>, Options<AdminDeleteUserData>> => {
    const mutationOptions: UseMutationOptions<AdminDeleteUserResponse, AxiosError<DefaultError>, Options<AdminDeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await adminDeleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete user
 *
 * Admin endpoint: soft-delete the local user (and profile) and permanently delete the identity from the identity provider
 */
export const useAdminDeleteUserMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<AdminDeleteUserResponse, AxiosError<DefaultError>, Options<AdminDeleteUserData>>, 'mutationFn'>>) => useMutation({ ...adminDeleteUserMutation(), ...mutationOptions });

/**
 * Login with email and password
 *
 * Authenticate a user with email and password via the identity provider
 */
export const loginWithEmailAndPasswordMutation = (options?: Partial<Options<LoginWithEmailAndPasswordData>>): UseMutationOptions<LoginWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<LoginWithEmailAndPasswordData>> => {
    const mutationOptions: UseMutationOptions<LoginWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<LoginWithEmailAndPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginWithEmailAndPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login with email and password
 *
 * Authenticate a user with email and password via the identity provider
 */
export const useLoginWithEmailAndPasswordMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<LoginWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<LoginWithEmailAndPasswordData>>, 'mutationFn'>>) => useMutation({ ...loginWithEmailAndPasswordMutation(), ...mutationOptions });

/**
 * Logout
 *
 * Invalidate the current session and clear the session cookie
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 *
 * Invalidate the current session and clear the session cookie
 */
export const useLogoutMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>>, 'mutationFn'>>) => useMutation({ ...logoutMutation(), ...mutationOptions });

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

/**
 * Get current authenticated user
 *
 * Return basic information about the current user by verifying the session cookie
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, AxiosError<DefaultError>, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

/**
 * Get current authenticated user
 *
 * Return basic information about the current user by verifying the session cookie
 */
export const useGetCurrentUserQuery = (options?: Options<GetCurrentUserData>) => useQuery(getCurrentUserOptions(options));

/**
 * OAuth authorize
 *
 * Start the OAuth authorization code flow
 */
export const authorizeMutation = (options?: Partial<Options<AuthorizeData>>): UseMutationOptions<AuthorizeResponse, AxiosError<DefaultError>, Options<AuthorizeData>> => {
    const mutationOptions: UseMutationOptions<AuthorizeResponse, AxiosError<DefaultError>, Options<AuthorizeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authorize({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * OAuth authorize
 *
 * Start the OAuth authorization code flow
 */
export const useAuthorizeMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<AuthorizeResponse, AxiosError<DefaultError>, Options<AuthorizeData>>, 'mutationFn'>>) => useMutation({ ...authorizeMutation(), ...mutationOptions });

/**
 * Register with email and password
 *
 * Register a new user with email and password via the identity provider
 */
export const registerWithEmailAndPasswordMutation = (options?: Partial<Options<RegisterWithEmailAndPasswordData>>): UseMutationOptions<RegisterWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<RegisterWithEmailAndPasswordData>> => {
    const mutationOptions: UseMutationOptions<RegisterWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<RegisterWithEmailAndPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerWithEmailAndPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register with email and password
 *
 * Register a new user with email and password via the identity provider
 */
export const useRegisterWithEmailAndPasswordMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<RegisterWithEmailAndPasswordResponse, AxiosError<DefaultError>, Options<RegisterWithEmailAndPasswordData>>, 'mutationFn'>>) => useMutation({ ...registerWithEmailAndPasswordMutation(), ...mutationOptions });

/**
 * Create a new issue attachment
 *
 * Create a new issue attachment
 */
export const createAttachmentMutation = (options?: Partial<Options<CreateAttachmentData>>): UseMutationOptions<unknown, AxiosError<CreateAttachmentError>, Options<CreateAttachmentData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CreateAttachmentError>, Options<CreateAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a new issue attachment
 *
 * Create a new issue attachment
 */
export const useCreateAttachmentMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<CreateAttachmentError>, Options<CreateAttachmentData>>, 'mutationFn'>>) => useMutation({ ...createAttachmentMutation(), ...mutationOptions });
