/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailVerificationRouteImport } from './routes/email-verification'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedIItemIdRouteImport } from './routes/_authenticated/i.$itemId'
import { Route as AuthenticatedWorkspaceIdHomeRouteImport } from './routes/_authenticated/$workspaceId.home'
import { Route as AuthenticatedWorkspaceIdVLViewIdRouteImport } from './routes/_authenticated/$workspaceId.v.l.$viewId'
import { Route as AuthenticatedWorkspaceIdVBViewIdRouteImport } from './routes/_authenticated/$workspaceId.v.b.$viewId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerificationRoute = EmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIItemIdRoute = AuthenticatedIItemIdRouteImport.update({
  id: '/i/$itemId',
  path: '/i/$itemId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceIdHomeRoute =
  AuthenticatedWorkspaceIdHomeRouteImport.update({
    id: '/$workspaceId/home',
    path: '/$workspaceId/home',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceIdVLViewIdRoute =
  AuthenticatedWorkspaceIdVLViewIdRouteImport.update({
    id: '/$workspaceId/v/l/$viewId',
    path: '/$workspaceId/v/l/$viewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceIdVBViewIdRoute =
  AuthenticatedWorkspaceIdVBViewIdRouteImport.update({
    id: '/$workspaceId/v/b/$viewId',
    path: '/$workspaceId/v/b/$viewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/email-verification': typeof EmailVerificationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/me': typeof AuthenticatedMeRoute
  '/$workspaceId/home': typeof AuthenticatedWorkspaceIdHomeRoute
  '/i/$itemId': typeof AuthenticatedIItemIdRoute
  '/$workspaceId/v/b/$viewId': typeof AuthenticatedWorkspaceIdVBViewIdRoute
  '/$workspaceId/v/l/$viewId': typeof AuthenticatedWorkspaceIdVLViewIdRoute
}
export interface FileRoutesByTo {
  '/email-verification': typeof EmailVerificationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/me': typeof AuthenticatedMeRoute
  '/': typeof AuthenticatedIndexRoute
  '/$workspaceId/home': typeof AuthenticatedWorkspaceIdHomeRoute
  '/i/$itemId': typeof AuthenticatedIItemIdRoute
  '/$workspaceId/v/b/$viewId': typeof AuthenticatedWorkspaceIdVBViewIdRoute
  '/$workspaceId/v/l/$viewId': typeof AuthenticatedWorkspaceIdVLViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/email-verification': typeof EmailVerificationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$workspaceId/home': typeof AuthenticatedWorkspaceIdHomeRoute
  '/_authenticated/i/$itemId': typeof AuthenticatedIItemIdRoute
  '/_authenticated/$workspaceId/v/b/$viewId': typeof AuthenticatedWorkspaceIdVBViewIdRoute
  '/_authenticated/$workspaceId/v/l/$viewId': typeof AuthenticatedWorkspaceIdVLViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-verification'
    | '/login'
    | '/signup'
    | '/me'
    | '/$workspaceId/home'
    | '/i/$itemId'
    | '/$workspaceId/v/b/$viewId'
    | '/$workspaceId/v/l/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/email-verification'
    | '/login'
    | '/signup'
    | '/me'
    | '/'
    | '/$workspaceId/home'
    | '/i/$itemId'
    | '/$workspaceId/v/b/$viewId'
    | '/$workspaceId/v/l/$viewId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/email-verification'
    | '/login'
    | '/signup'
    | '/_authenticated/me'
    | '/_authenticated/'
    | '/_authenticated/$workspaceId/home'
    | '/_authenticated/i/$itemId'
    | '/_authenticated/$workspaceId/v/b/$viewId'
    | '/_authenticated/$workspaceId/v/l/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EmailVerificationRoute: typeof EmailVerificationRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verification': {
      id: '/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof EmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/i/$itemId': {
      id: '/_authenticated/i/$itemId'
      path: '/i/$itemId'
      fullPath: '/i/$itemId'
      preLoaderRoute: typeof AuthenticatedIItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$workspaceId/home': {
      id: '/_authenticated/$workspaceId/home'
      path: '/$workspaceId/home'
      fullPath: '/$workspaceId/home'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$workspaceId/v/l/$viewId': {
      id: '/_authenticated/$workspaceId/v/l/$viewId'
      path: '/$workspaceId/v/l/$viewId'
      fullPath: '/$workspaceId/v/l/$viewId'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdVLViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$workspaceId/v/b/$viewId': {
      id: '/_authenticated/$workspaceId/v/b/$viewId'
      path: '/$workspaceId/v/b/$viewId'
      fullPath: '/$workspaceId/v/b/$viewId'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdVBViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkspaceIdHomeRoute: typeof AuthenticatedWorkspaceIdHomeRoute
  AuthenticatedIItemIdRoute: typeof AuthenticatedIItemIdRoute
  AuthenticatedWorkspaceIdVBViewIdRoute: typeof AuthenticatedWorkspaceIdVBViewIdRoute
  AuthenticatedWorkspaceIdVLViewIdRoute: typeof AuthenticatedWorkspaceIdVLViewIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkspaceIdHomeRoute: AuthenticatedWorkspaceIdHomeRoute,
  AuthenticatedIItemIdRoute: AuthenticatedIItemIdRoute,
  AuthenticatedWorkspaceIdVBViewIdRoute: AuthenticatedWorkspaceIdVBViewIdRoute,
  AuthenticatedWorkspaceIdVLViewIdRoute: AuthenticatedWorkspaceIdVLViewIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EmailVerificationRoute: EmailVerificationRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
