// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetIdentityGetSessionData, GetIdentityGetSessionResponses, GetIdentityGetTokenSessionData, GetIdentityGetTokenSessionResponses, GetIdentityMeData, GetIdentityMeResponses, GetIdentityOauthAuthorizeData, GetIdentityOauthAuthorizeResponses, GetIdentityOauthConsentData, GetIdentityOauthConsentResponses, GetIdentityVerifyEmailData, GetIdentityVerifyEmailResponses, PostAttachmentsByIssueIdData, PostAttachmentsByIssueIdResponses, PostIdentityLogoutData, PostIdentityLogoutResponses, PostIdentityOauthConsentAcceptData, PostIdentityOauthConsentAcceptResponses, PostIdentityOauthConsentRejectData, PostIdentityOauthConsentRejectResponses, PostIdentityOauthTokenData, PostIdentityOauthTokenResponses, PostIdentityRegisterData, PostIdentityRegisterResponses, PostIdentityResendVerificationEmailData, PostIdentityResendVerificationEmailResponses, PostIdentitySigninData, PostIdentitySigninResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postIdentitySignin = <ThrowOnError extends boolean = false>(options?: Options<PostIdentitySigninData, ThrowOnError>): RequestResult<PostIdentitySigninResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostIdentitySigninResponses, unknown, ThrowOnError>({ url: '/identity/signin', ...options });

export const postIdentityLogout = <ThrowOnError extends boolean = false>(options?: Options<PostIdentityLogoutData, ThrowOnError>): RequestResult<PostIdentityLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostIdentityLogoutResponses, unknown, ThrowOnError>({ url: '/identity/logout', ...options });

export const getIdentityMe = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityMeData, ThrowOnError>): RequestResult<GetIdentityMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityMeResponses, unknown, ThrowOnError>({ url: '/identity/me', ...options });

export const getIdentityGetSession = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityGetSessionData, ThrowOnError>): RequestResult<GetIdentityGetSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityGetSessionResponses, unknown, ThrowOnError>({ url: '/identity/getSession', ...options });

export const getIdentityGetTokenSession = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityGetTokenSessionData, ThrowOnError>): RequestResult<GetIdentityGetTokenSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityGetTokenSessionResponses, unknown, ThrowOnError>({ url: '/identity/getTokenSession', ...options });

export const getIdentityOauthAuthorize = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityOauthAuthorizeData, ThrowOnError>): RequestResult<GetIdentityOauthAuthorizeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityOauthAuthorizeResponses, unknown, ThrowOnError>({ url: '/identity/oauth/authorize', ...options });

export const getIdentityOauthConsent = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityOauthConsentData, ThrowOnError>): RequestResult<GetIdentityOauthConsentResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityOauthConsentResponses, unknown, ThrowOnError>({ url: '/identity/oauth/consent', ...options });

export const postIdentityOauthConsentAccept = <ThrowOnError extends boolean = false>(options?: Options<PostIdentityOauthConsentAcceptData, ThrowOnError>): RequestResult<PostIdentityOauthConsentAcceptResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostIdentityOauthConsentAcceptResponses, unknown, ThrowOnError>({ url: '/identity/oauth/consent/accept', ...options });

export const postIdentityOauthConsentReject = <ThrowOnError extends boolean = false>(options?: Options<PostIdentityOauthConsentRejectData, ThrowOnError>): RequestResult<PostIdentityOauthConsentRejectResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostIdentityOauthConsentRejectResponses, unknown, ThrowOnError>({ url: '/identity/oauth/consent/reject', ...options });

export const postIdentityOauthToken = <ThrowOnError extends boolean = false>(options?: Options<PostIdentityOauthTokenData, ThrowOnError>): RequestResult<PostIdentityOauthTokenResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostIdentityOauthTokenResponses, unknown, ThrowOnError>({ url: '/identity/oauth/token', ...options });

export const postIdentityRegister = <ThrowOnError extends boolean = false>(options?: Options<PostIdentityRegisterData, ThrowOnError>): RequestResult<PostIdentityRegisterResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostIdentityRegisterResponses, unknown, ThrowOnError>({ url: '/identity/register', ...options });

export const getIdentityVerifyEmail = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityVerifyEmailData, ThrowOnError>): RequestResult<GetIdentityVerifyEmailResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityVerifyEmailResponses, unknown, ThrowOnError>({ url: '/identity/verifyEmail', ...options });

export const postIdentityResendVerificationEmail = <ThrowOnError extends boolean = false>(options?: Options<PostIdentityResendVerificationEmailData, ThrowOnError>): RequestResult<PostIdentityResendVerificationEmailResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostIdentityResendVerificationEmailResponses, unknown, ThrowOnError>({ url: '/identity/resendVerificationEmail', ...options });

export const postAttachmentsByIssueId = <ThrowOnError extends boolean = false>(options: Options<PostAttachmentsByIssueIdData, ThrowOnError>): RequestResult<PostAttachmentsByIssueIdResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostAttachmentsByIssueIdResponses, unknown, ThrowOnError>({ url: '/attachments/{issueId}', ...options });
