// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AcceptConsentChallengeData, AcceptConsentChallengeResponses, AuthorizeData, CreateAttachmentData, CreateAttachmentErrors, CreateAttachmentResponses, ExchangeTokenData, ExchangeTokenResponses, GetConsentChallengeData, GetConsentChallengeResponses, GetCurrentUserData, GetCurrentUserResponses, GetSessionIdentityData, GetSessionIdentityResponses, GetTokenSessionIdentityData, GetTokenSessionIdentityResponses, LogoutData, LogoutResponses, RegisterData, RegisterResponses, RejectConsentChallengeData, RejectConsentChallengeResponses, ResendVerificationEmailData, ResendVerificationEmailResponses, SignInWithEmailAndPasswordData, SignInWithEmailAndPasswordResponses, VerifyEmailData, VerifyEmailResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Sign in with email and password
 *
 * Authenticate a user with email and password via the identity provider. Sets the session cookie. When a login_challenge is present, returns redirectTo for the OAuth provider.
 */
export const signInWithEmailAndPassword = <ThrowOnError extends boolean = false>(options: Options<SignInWithEmailAndPasswordData, ThrowOnError>): RequestResult<SignInWithEmailAndPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<SignInWithEmailAndPasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/signin',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 *
 * Invalidate the current session and clear the session cookie
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/logout',
    ...options
});

/**
 * Get current authenticated user
 *
 * Return basic information about the current user by verifying the session cookie
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/me',
    ...options
});

/**
 * Resolve session identity
 *
 * Verify the session cookie against Ory Kratos (SDK FrontendApi.toSession) and return the authenticated identity. Used by other services via @pine/identity-client.
 */
export const getSessionIdentity = <ThrowOnError extends boolean = false>(options?: Options<GetSessionIdentityData, ThrowOnError>): RequestResult<GetSessionIdentityResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSessionIdentityResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/getSession',
    ...options
});

/**
 * Resolve identity from OAuth access token
 *
 * Introspect an OAuth provider access token (Authorization: Bearer) and return the authenticated identity. Used by other services via @pine/identity-client.
 */
export const getTokenSessionIdentity = <ThrowOnError extends boolean = false>(options?: Options<GetTokenSessionIdentityData, ThrowOnError>): RequestResult<GetTokenSessionIdentityResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetTokenSessionIdentityResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/identity/getTokenSession',
    ...options
});

/**
 * OAuth authorize
 *
 * Start the OAuth authorization code flow. Redirects (302) to the OAuth provider authorization endpoint.
 */
export const authorize = <ThrowOnError extends boolean = false>(options: Options<AuthorizeData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => (options.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/identity/oauth/authorize', ...options });

/**
 * OAuth consent challenge
 *
 * Load OAuth consent challenge details by consent_challenge
 */
export const getConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<GetConsentChallengeData, ThrowOnError>): RequestResult<GetConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/consent',
    ...options
});

/**
 * Accept OAuth consent
 *
 * Accept an OAuth consent challenge with granted scopes
 */
export const acceptConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<AcceptConsentChallengeData, ThrowOnError>): RequestResult<AcceptConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).post<AcceptConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/consent/accept',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reject OAuth consent
 *
 * Reject an OAuth consent challenge when the user denies access
 */
export const rejectConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<RejectConsentChallengeData, ThrowOnError>): RequestResult<RejectConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).post<RejectConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/consent/reject',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * OAuth token
 *
 * Exchange an authorization code for access (and optional refresh/id) tokens and set them as HTTP-only cookies
 */
export const exchangeToken = <ThrowOnError extends boolean = false>(options: Options<ExchangeTokenData, ThrowOnError>): RequestResult<ExchangeTokenResponses, unknown, ThrowOnError> => (options.client ?? client).post<ExchangeTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register
 *
 * Register a new user with email and password via the identity provider
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify email with Kratos code
 *
 * Complete email verification using the one-time code from the Kratos verification email
 */
export const verifyEmail = <ThrowOnError extends boolean = false>(options: Options<VerifyEmailData, ThrowOnError>): RequestResult<VerifyEmailResponses, unknown, ThrowOnError> => (options.client ?? client).get<VerifyEmailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/verifyEmail',
    ...options
});

/**
 * Resend verification email
 *
 * Request a new email verification code. Always returns success to avoid revealing whether the email is registered.
 */
export const resendVerificationEmail = <ThrowOnError extends boolean = false>(options: Options<ResendVerificationEmailData, ThrowOnError>): RequestResult<ResendVerificationEmailResponses, unknown, ThrowOnError> => (options.client ?? client).post<ResendVerificationEmailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/resendVerificationEmail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a new issue attachment
 *
 * Create a new issue attachment
 */
export const createAttachment = <ThrowOnError extends boolean = false>(options: Options<CreateAttachmentData, ThrowOnError>): RequestResult<CreateAttachmentResponses, CreateAttachmentErrors, ThrowOnError> => (options.client ?? client).post<CreateAttachmentResponses, CreateAttachmentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/attachments/{issueId}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
