// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5003' | 'http://127.0.0.1:5006' | 'http://127.0.0.1:5006' | 'http://127.0.0.1:5006' | 'http://127.0.0.1:5006' | (string & {});
};

export type SignInWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: {
        login_challenge?: string;
    };
    url: '/identity/signin';
};

export type SignInWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            identity: {
                id: string;
                email: string;
                emailVerified?: boolean;
            };
            redirectTo?: string;
        };
    };
};

export type SignInWithEmailAndPasswordResponse = SignInWithEmailAndPasswordResponses[keyof SignInWithEmailAndPasswordResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/logout';
};

export type LogoutResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/me';
};

export type GetCurrentUserResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified?: boolean;
        };
        profile: {
            id: string;
            identityId: string;
            firstName: string;
            middleName?: string | unknown;
            lastName?: string | unknown;
            gender?: string | unknown;
            description?: string | unknown;
            photoUrl?: string | unknown;
            fullName: string;
        } | unknown;
    };
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetIdentityFromSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/getIdentityFromSession';
};

export type GetIdentityFromSessionResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified: boolean;
        };
    };
};

export type GetIdentityFromSessionResponse = GetIdentityFromSessionResponses[keyof GetIdentityFromSessionResponses];

export type GetIdentityFromAccessTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/getIdentityFromAccessToken';
};

export type GetIdentityFromAccessTokenResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified: boolean;
        };
    };
};

export type GetIdentityFromAccessTokenResponse = GetIdentityFromAccessTokenResponses[keyof GetIdentityFromAccessTokenResponses];

export type AuthorizeData = {
    body?: never;
    path?: never;
    query: {
        response_type: 'code';
        client_id: string;
        redirect_uri: string;
        scope: string;
        state: string;
        code_challenge?: string;
        code_challenge_method?: 'S256' | 'plain';
        nonce?: string;
    };
    url: '/identity/oauth/authorize';
};

export type GetConsentChallengeData = {
    body?: never;
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/identity/oauth/consent';
};

export type GetConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        challenge: string;
        skip: boolean;
        subject?: string;
        client: {
            id: string;
            name?: string;
            redirectUris?: Array<string>;
        };
        requestedScope: Array<string>;
        requestUrl?: string;
        loginChallenge?: string;
        loginSessionId?: string;
    };
};

export type GetConsentChallengeResponse = GetConsentChallengeResponses[keyof GetConsentChallengeResponses];

export type AcceptConsentChallengeData = {
    body: {
        grantScope: Array<string>;
        remember?: boolean;
        rememberFor?: number;
    };
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/identity/oauth/consent/accept';
};

export type AcceptConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        redirectTo: string;
    };
};

export type AcceptConsentChallengeResponse = AcceptConsentChallengeResponses[keyof AcceptConsentChallengeResponses];

export type RejectConsentChallengeData = {
    body: {
        error?: string;
        errorDescription?: string;
    };
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/identity/oauth/consent/reject';
};

export type RejectConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        redirectTo: string;
    };
};

export type RejectConsentChallengeResponse = RejectConsentChallengeResponses[keyof RejectConsentChallengeResponses];

export type ExchangeTokenData = {
    body: {
        grant_type: 'authorization_code';
        code: string;
        client_id: string;
        redirect_uri: string;
        code_verifier: string;
    };
    path?: never;
    query?: never;
    url: '/identity/oauth/token';
};

export type ExchangeTokenResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type ExchangeTokenResponse = ExchangeTokenResponses[keyof ExchangeTokenResponses];

export type RegisterData = {
    body: {
        email: string;
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/identity/register';
};

export type RegisterResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type VerifyEmailData = {
    body?: never;
    path?: never;
    query: {
        flow: string;
        code: string;
    };
    url: '/identity/verifyEmail';
};

export type VerifyEmailResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResendVerificationEmailData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/identity/resendVerificationEmail';
};

export type ResendVerificationEmailResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type ResendVerificationEmailResponse = ResendVerificationEmailResponses[keyof ResendVerificationEmailResponses];

export type CreateAttachmentData = {
    body: {
        file: Blob | File;
    };
    path: {
        issueId: string;
    };
    query?: never;
    url: '/attachments/{issueId}';
};

export type CreateAttachmentErrors = {
    /**
     * Error response
     */
    400: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
    /**
     * Error response
     */
    500: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
};

export type CreateAttachmentError = CreateAttachmentErrors[keyof CreateAttachmentErrors];

export type CreateAttachmentResponses = {
    /**
     * Created successfully
     */
    201: unknown;
};

export type CheckRelationshipData = {
    body: {
        namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
        object: string;
        relation: string;
        subject: string;
    };
    path?: never;
    query?: never;
    url: '/authorization/checkRelationship';
};

export type CheckRelationshipResponses = {
    /**
     * Default Response
     */
    200: {
        allowed: boolean;
    };
};

export type CheckRelationshipResponse = CheckRelationshipResponses[keyof CheckRelationshipResponses];

export type EnsureRelationshipData = {
    body: {
        object: {
            namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
            id: string;
        };
        relation: string;
        subject?: {
            namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
            id: string;
        };
        subjectSet?: {
            namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
            id: string;
            relation: string;
        };
    };
    path?: never;
    query?: never;
    url: '/authorization/ensureRelationship';
};

export type EnsureRelationshipResponses = {
    /**
     * Default Response
     */
    200: {
        created: boolean;
    };
};

export type EnsureRelationshipResponse = EnsureRelationshipResponses[keyof EnsureRelationshipResponses];

export type DeleteRelationshipData = {
    body: {
        object: {
            namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
            id: string;
        };
        relation: string;
        subject?: {
            namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
            id: string;
        };
        subjectSet?: {
            namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
            id: string;
            relation: string;
        };
    };
    path?: never;
    query?: never;
    url: '/authorization/deleteRelationship';
};

export type DeleteRelationshipResponses = {
    /**
     * Default Response
     */
    200: {
        deleted: boolean;
    };
};

export type DeleteRelationshipResponse = DeleteRelationshipResponses[keyof DeleteRelationshipResponses];

export type ListRelationshipsData = {
    body: {
        namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
        object: string;
        relation?: string;
    };
    path?: never;
    query?: never;
    url: '/authorization/listRelationships';
};

export type ListRelationshipsResponses = {
    /**
     * Default Response
     */
    200: {
        relationships: Array<{
            object: {
                namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
                id: string;
            };
            relation: string;
            subject?: {
                namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
                id: string;
            };
            subjectSet?: {
                namespace: 'identity' | 'profile' | 'platform' | 'tenant' | 'organization' | 'product' | 'brand' | 'role' | 'permission';
                id: string;
                relation: string;
            };
        }>;
    };
};

export type ListRelationshipsResponse = ListRelationshipsResponses[keyof ListRelationshipsResponses];
