// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5000' | 'http://127.0.0.1:5003' | (string & {});
};

export type LoginWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: {
        login_challenge?: string;
    };
    url: '/identity/login';
};

export type LoginWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified?: boolean;
        };
        redirectTo?: string;
    };
};

export type LoginWithEmailAndPasswordResponse = LoginWithEmailAndPasswordResponses[keyof LoginWithEmailAndPasswordResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/logout';
};

export type LogoutResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/me';
};

export type GetCurrentUserResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified?: boolean;
        };
    };
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetSessionIdentityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/session';
};

export type GetSessionIdentityResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified?: boolean;
        };
    };
};

export type GetSessionIdentityResponse = GetSessionIdentityResponses[keyof GetSessionIdentityResponses];

export type AuthorizeData = {
    body?: never;
    path?: never;
    query: {
        response_type: 'code';
        client_id: string;
        redirect_uri: string;
        scope: string;
        state: string;
        code_challenge?: string;
        code_challenge_method?: 'S256' | 'plain';
        nonce?: string;
    };
    url: '/identity/oauth/authorize';
};

export type GetConsentChallengeData = {
    body?: never;
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/identity/oauth/consent';
};

export type GetConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        challenge: string;
        skip: boolean;
        subject?: string;
        client: {
            id: string;
            name?: string;
            redirectUris?: Array<string>;
        };
        requestedScope: Array<string>;
        requestUrl?: string;
        loginChallenge?: string;
        loginSessionId?: string;
    };
};

export type GetConsentChallengeResponse = GetConsentChallengeResponses[keyof GetConsentChallengeResponses];

export type AcceptConsentChallengeData = {
    body: {
        grantScope: Array<string>;
        remember?: boolean;
        rememberFor?: number;
    };
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/identity/oauth/consent/accept';
};

export type AcceptConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        redirectTo: string;
    };
};

export type AcceptConsentChallengeResponse = AcceptConsentChallengeResponses[keyof AcceptConsentChallengeResponses];

export type RejectConsentChallengeData = {
    body: {
        error?: string;
        errorDescription?: string;
    };
    path?: never;
    query: {
        consent_challenge: string;
    };
    url: '/identity/oauth/consent/reject';
};

export type RejectConsentChallengeResponses = {
    /**
     * Default Response
     */
    200: {
        redirectTo: string;
    };
};

export type RejectConsentChallengeResponse = RejectConsentChallengeResponses[keyof RejectConsentChallengeResponses];

export type ExchangeTokenData = {
    body: {
        grant_type: 'authorization_code';
        code: string;
        client_id: string;
        redirect_uri: string;
        code_verifier: string;
    };
    path?: never;
    query?: never;
    url: '/identity/oauth/token';
};

export type ExchangeTokenResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type ExchangeTokenResponse = ExchangeTokenResponses[keyof ExchangeTokenResponses];

export type RegisterWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/identity/registerWithEmailAndPassword';
};

export type RegisterWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type RegisterWithEmailAndPasswordResponse = RegisterWithEmailAndPasswordResponses[keyof RegisterWithEmailAndPasswordResponses];

export type CreateAttachmentData = {
    body: {
        file: Blob | File;
    };
    path: {
        issueId: string;
    };
    query?: never;
    url: '/attachments/{issueId}';
};

export type CreateAttachmentErrors = {
    /**
     * Error response
     */
    400: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
    /**
     * Error response
     */
    500: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
};

export type CreateAttachmentError = CreateAttachmentErrors[keyof CreateAttachmentErrors];

export type CreateAttachmentResponses = {
    /**
     * Created successfully
     */
    201: unknown;
};
