#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<EOF
CREATE ROLE identity WITH LOGIN PASSWORD '${POSTGRES_IDENTITY_PASSWORD}';
CREATE ROLE issues WITH LOGIN PASSWORD '${POSTGRES_ISSUES_PASSWORD}';
CREATE ROLE mail WITH LOGIN PASSWORD '${POSTGRES_MAIL_PASSWORD}';
CREATE ROLE attachment WITH LOGIN PASSWORD '${POSTGRES_ATTACHMENT_PASSWORD}';
CREATE ROLE inventory WITH LOGIN PASSWORD '${POSTGRES_INVENTORY_PASSWORD}';

CREATE DATABASE identity OWNER identity;
CREATE DATABASE issues OWNER issues;
CREATE DATABASE mail OWNER mail;
CREATE DATABASE attachment OWNER attachment;
CREATE DATABASE inventory OWNER inventory;
EOF