export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  UserRepository: Symbol.for("IUserRepository"),
  UserProfileRepository: Symbol.for("IUserProfileRepository"),
  UserService: Symbol.for("IUserService"),
  UserProfileService: Symbol.for("IUserProfileService"),
  KratosClient: Symbol.for("KratosClient"),
  IdentityProvider: Symbol.for("IIdentityProvider"),
  HydraClient: Symbol.for("HydraClient"),
  OAuthProvider: Symbol.for("IOAuthProvider"),
  RegistrationService: Symbol.for("IRegistrationService"),
  LoginService: Symbol.for("ILoginService"),
  LogoutService: Symbol.for("ILogoutService"),
  MeService: Symbol.for("IMeService"),
  OAuthService: Symbol.for("IOAuthService"),
  AdminService: Symbol.for("IAdminService"),
} as const;
