// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateAttachmentData, CreateAttachmentErrors, CreateAttachmentResponses, LoginWithEmailAndPasswordData, LoginWithEmailAndPasswordResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login with email and password
 *
 * Authenticate a user with email and password via the identity provider
 */
export const loginWithEmailAndPassword = <ThrowOnError extends boolean = false>(options: Options<LoginWithEmailAndPasswordData, ThrowOnError>): RequestResult<LoginWithEmailAndPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<LoginWithEmailAndPasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a new issue attachment
 *
 * Create a new issue attachment
 */
export const createAttachment = <ThrowOnError extends boolean = false>(options: Options<CreateAttachmentData, ThrowOnError>): RequestResult<CreateAttachmentResponses, CreateAttachmentErrors, ThrowOnError> => (options.client ?? client).post<CreateAttachmentResponses, CreateAttachmentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/attachments/{issueId}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
