mutation UpdateRole($input: UpdateRoleInput!) {
  updateRole(input: $input) {
    id
    key
    name
    description
    system
    createdAt
    updatedAt
    capabilities {
      id
      key
      service
      resource
      action
    }
  }
}
