export enum IssuePermissions {
  ViewIssue = "issue:view-issue",
  EditIssue = "issue:edit-issue",
  EditIssueStatus = "issue:edit-issue-status",
  EditIssueResolution = "issue:edit-issue-resolution",
  ArchiveIssue = "issue:archive-issue",
  CreateAttachment = "issue:create-attachment",
  ViewAttachment = "issue:view-attachment",
  EditAttachment = "issue:edit-attachment",
  ArchiveAttachment = "issue:archive-attachment",
  CreateTask = "issue:create-task",
  ViewTask = "issue:view-task",
  EditTask = "issue:edit-task",
  ArchiveTask = "issue:archive-task",
  CreateComment = "issue:create-comment",
  ViewComment = "issue:view-comment",
  EditComment = "issue:edit-comment",
  ArchiveComment = "issue:archive-comment",
}
