apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker-services
build:
  artifacts:
    - image: sourabhrawatcc/attachment
      context: ../..
      docker:
        dockerfile: Dockerfile
        target: attachment

    - image: sourabhrawatcc/email
      context: ../..
      docker:
        dockerfile: Dockerfile
        target: email

    - image: sourabhrawatcc/identity-service
      context: ../..
      docker:
        dockerfile: Dockerfile
        target: identity-service

    - image: sourabhrawatcc/issue-tracker
      context: ../..
      docker:
        dockerfile: Dockerfile
        target: issue-tracker

  local:
    concurrency: 0
deploy:
  helm:
    releases:
      - name: attachment
        chartPath: ../../infra/k8s/microservice
        valuesFiles:
          - ../../infra/k8s/microservice/attachment.values.yaml

      - name: email
        chartPath: ../../infra/k8s/microservice
        valuesFiles:
          - ../../infra/k8s/microservice/email.values.yaml

      - name: identity
        chartPath: ../../infra/k8s/microservice
        valuesFiles:
          - ../../infra/k8s/microservice/identity-service.values.yaml

      - name: issue-tracker
        chartPath: ../../infra/k8s/microservice
        valuesFiles:
          - ../../infra/k8s/microservice/issue-tracker.values.yaml
