export const CONTENT_ATTACHMENT_SCAN_STATUS = {
  PENDING: "PENDING",
  SCANNING: "SCANNING",
  PASSED: "PASSED",
  FLAGGED: "FLAGGED",
  FAILED: "FAILED",
} as const;

export type ContentAttachmentScanStatus =
  (typeof CONTENT_ATTACHMENT_SCAN_STATUS)[keyof typeof CONTENT_ATTACHMENT_SCAN_STATUS];
