mutation CreatePhotoUploadRequest($input: CreatePhotoUploadRequestInput!) {
  createPhotoUploadRequest(input: $input) {
    uploadRequestId
    url
    expiresAt
    headers {
      key
      value
    }
  }
}
