import type { CapabilityDefinition } from "./CapabilityDefinition";
import { BRANDS } from "./Brands";
import { CAPABILITIES } from "./Capabilities";
import { CAPABILITY_GRANTS } from "./CapabilityGrants";
import { TENANTS } from "./Tenants";
import { ORGANIZATIONS } from "./Organizations";
import { PLATFORM_ROLE } from "./PlatformRoles";
import { PLATFORM_ROLE_ASSIGNMENT } from "./PlatformRoleAssignments";
import { PRODUCTS } from "./Products";
import { ROLES } from "./Roles";

export const ALL_CAPABILITIES = [
  CAPABILITIES.READ,
  CAPABILITIES.CREATE,
  CAPABILITIES.UPDATE,
  CAPABILITIES.DELETE,
  ROLES.READ,
  ROLES.CREATE,
  ROLES.UPDATE,
  ROLES.DELETE,
  CAPABILITY_GRANTS.READ,
  CAPABILITY_GRANTS.CREATE,
  CAPABILITY_GRANTS.UPDATE,
  CAPABILITY_GRANTS.DELETE,
  TENANTS.READ,
  TENANTS.CREATE,
  TENANTS.SUSPEND,
  TENANTS.CONFIGURE,
  TENANTS.ASSIGN_ADMIN,
  ORGANIZATIONS.READ,
  ORGANIZATIONS.CREATE,
  ORGANIZATIONS.UPDATE,
  ORGANIZATIONS.DELETE,
  PLATFORM_ROLE.READ,
  PLATFORM_ROLE.CREATE,
  PLATFORM_ROLE.UPDATE,
  PLATFORM_ROLE.DELETE,
  PLATFORM_ROLE_ASSIGNMENT.READ,
  PLATFORM_ROLE_ASSIGNMENT.CREATE,
  PLATFORM_ROLE_ASSIGNMENT.UPDATE,
  PLATFORM_ROLE_ASSIGNMENT.DELETE,
  PRODUCTS.READ,
  PRODUCTS.CREATE,
  PRODUCTS.UPDATE,
  PRODUCTS.DELETE,
  BRANDS.READ,
  BRANDS.CREATE,
  BRANDS.UPDATE,
  BRANDS.DELETE,
] as const satisfies readonly CapabilityDefinition[];

export type CapabilityKey = (typeof ALL_CAPABILITIES)[number]["key"];
