import type { CapabilityDefinition } from "./CapabilityDefinition";
import { BRANDS } from "./Brands";
import { CAPABILITY_GRANTS } from "./CapabilityGrants";
import { TENANTS } from "./Tenants";
import { ORGANIZATIONS } from "./Organizations";
import { PLATFORM_ROLE } from "./PlatformRoles";
import { PLATFORM_MEMBER } from "./PlatformMembers";
import { PRODUCTS } from "./Products";
import { ROLES } from "./Roles";

export const ALL_CAPABILITIES = [
  ROLES.READ,
  ROLES.CREATE,
  ROLES.UPDATE,
  ROLES.DELETE,
  CAPABILITY_GRANTS.READ,
  CAPABILITY_GRANTS.CREATE,
  CAPABILITY_GRANTS.UPDATE,
  CAPABILITY_GRANTS.DELETE,
  TENANTS.READ,
  TENANTS.CREATE,
  TENANTS.SUSPEND,
  TENANTS.CONFIGURE,
  TENANTS.ASSIGN_ADMIN,
  ORGANIZATIONS.READ,
  ORGANIZATIONS.CREATE,
  ORGANIZATIONS.UPDATE,
  ORGANIZATIONS.DELETE,
  PLATFORM_ROLE.READ,
  PLATFORM_ROLE.CREATE,
  PLATFORM_ROLE.UPDATE,
  PLATFORM_ROLE.DELETE,
  PLATFORM_MEMBER.READ,
  PLATFORM_MEMBER.CREATE,
  PLATFORM_MEMBER.UPDATE,
  PLATFORM_MEMBER.DELETE,
  PRODUCTS.READ,
  PRODUCTS.CREATE,
  PRODUCTS.UPDATE,
  PRODUCTS.DELETE,
  BRANDS.READ,
  BRANDS.CREATE,
  BRANDS.UPDATE,
  BRANDS.DELETE,
] as const satisfies readonly CapabilityDefinition[];

export type CapabilityKey = (typeof ALL_CAPABILITIES)[number]["key"];
