export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  HttpServer: Symbol.for("IHttpServer"),
  IdentityRepository: Symbol.for("IIdentityRepository"),
  InventoryIdentitySyncConsumer: Symbol.for("InventoryIdentitySyncConsumer"),
  MeService: Symbol.for("IMeService"),
  BrandRepository: Symbol.for("IBrandRepository"),
  BrandSyncConsumer: Symbol.for("BrandSyncConsumer"),
  ProductRepository: Symbol.for("IProductRepository"),
  ProductUnitRepository: Symbol.for("IProductUnitRepository"),
  ProductSyncConsumer: Symbol.for("ProductSyncConsumer"),
} as const;
