// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AcceptConsentChallengeData, AcceptConsentChallengeResponses, AuthorizeData, CheckRelationshipData, CheckRelationshipResponses, CreateUploadTargetData, CreateUploadTargetResponses, DeleteRelationshipData, DeleteRelationshipResponses, EnsureRelationshipData, EnsureRelationshipResponses, ExchangeTokenData, ExchangeTokenResponses, GetConsentChallengeData, GetConsentChallengeResponses, GetCurrentUserData, GetCurrentUserResponses, GetIdentityFromAccessTokenData, GetIdentityFromAccessTokenResponses, GetIdentityFromSessionData, GetIdentityFromSessionResponses, ListRelationshipsData, ListRelationshipsResponses, LogoutData, LogoutResponses, RegisterData, RegisterResponses, RejectConsentChallengeData, RejectConsentChallengeResponses, ResendVerificationEmailData, ResendVerificationEmailResponses, SignInWithEmailAndPasswordData, SignInWithEmailAndPasswordResponses, UploadToTargetData, UploadToTargetResponses, VerifyEmailData, VerifyEmailResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Sign in with email and password
 *
 * Authenticate a user with email and password via the identity provider. Sets the session cookie. When a login_challenge is present, returns redirectTo for the OAuth provider.
 */
export const signInWithEmailAndPassword = <ThrowOnError extends boolean = false>(options: Options<SignInWithEmailAndPasswordData, ThrowOnError>): RequestResult<SignInWithEmailAndPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<SignInWithEmailAndPasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/signin',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 *
 * Invalidate the current session and clear the session cookie
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/logout',
    ...options
});

/**
 * Get current authenticated user
 *
 * Return basic information about the current user by verifying the session cookie
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/me',
    ...options
});

/**
 * Resolve session identity
 *
 * Verify the session cookie against Ory Kratos (SDK FrontendApi.toSession) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const getIdentityFromSession = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityFromSessionData, ThrowOnError>): RequestResult<GetIdentityFromSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityFromSessionResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/getIdentityFromSession',
    ...options
});

/**
 * Resolve identity from OAuth access token
 *
 * Introspect an OAuth provider access token (Authorization: Bearer) and return the authenticated identity. Used by other services via @pine/identity.
 */
export const getIdentityFromAccessToken = <ThrowOnError extends boolean = false>(options?: Options<GetIdentityFromAccessTokenData, ThrowOnError>): RequestResult<GetIdentityFromAccessTokenResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIdentityFromAccessTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/identity/getIdentityFromAccessToken',
    ...options
});

/**
 * OAuth authorize
 *
 * Start the OAuth authorization code flow. Redirects (302) to the OAuth provider authorization endpoint.
 */
export const authorize = <ThrowOnError extends boolean = false>(options: Options<AuthorizeData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => (options.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/identity/oauth/authorize', ...options });

/**
 * OAuth consent challenge
 *
 * Load OAuth consent challenge details by consent_challenge
 */
export const getConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<GetConsentChallengeData, ThrowOnError>): RequestResult<GetConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/consent',
    ...options
});

/**
 * Accept OAuth consent
 *
 * Accept an OAuth consent challenge with granted scopes
 */
export const acceptConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<AcceptConsentChallengeData, ThrowOnError>): RequestResult<AcceptConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).post<AcceptConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/consent/accept',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reject OAuth consent
 *
 * Reject an OAuth consent challenge when the user denies access
 */
export const rejectConsentChallenge = <ThrowOnError extends boolean = false>(options: Options<RejectConsentChallengeData, ThrowOnError>): RequestResult<RejectConsentChallengeResponses, unknown, ThrowOnError> => (options.client ?? client).post<RejectConsentChallengeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/consent/reject',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * OAuth token
 *
 * Exchange an authorization code for access (and optional refresh/id) tokens and set them as HTTP-only cookies
 */
export const exchangeToken = <ThrowOnError extends boolean = false>(options: Options<ExchangeTokenData, ThrowOnError>): RequestResult<ExchangeTokenResponses, unknown, ThrowOnError> => (options.client ?? client).post<ExchangeTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/oauth/token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register
 *
 * Register a new user with email and password via the identity provider
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify email with Kratos code
 *
 * Complete email verification using the one-time code from the Kratos verification email
 */
export const verifyEmail = <ThrowOnError extends boolean = false>(options: Options<VerifyEmailData, ThrowOnError>): RequestResult<VerifyEmailResponses, unknown, ThrowOnError> => (options.client ?? client).get<VerifyEmailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/verifyEmail',
    ...options
});

/**
 * Resend verification email
 *
 * Request a new email verification code. Always returns success to avoid revealing whether the email is registered.
 */
export const resendVerificationEmail = <ThrowOnError extends boolean = false>(options: Options<ResendVerificationEmailData, ThrowOnError>): RequestResult<ResendVerificationEmailResponses, unknown, ThrowOnError> => (options.client ?? client).post<ResendVerificationEmailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/identity/resendVerificationEmail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create upload target
 *
 * Create an upload target for uploading attachment files
 */
export const createUploadTarget = <ThrowOnError extends boolean = false>(options: Options<CreateUploadTargetData, ThrowOnError>): RequestResult<CreateUploadTargetResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateUploadTargetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/internal/attachments/createUploadTarget',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload file to upload target
 *
 * Upload file to upload target
 */
export const uploadToTarget = <ThrowOnError extends boolean = false>(options: Options<UploadToTargetData, ThrowOnError>): RequestResult<UploadToTargetResponses, unknown, ThrowOnError> => (options.client ?? client).put<UploadToTargetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/attachments/upload/{id}',
    ...options
});

/**
 * Check a graph relationship
 *
 * Check a Keto permission: namespace, object, relation, and subject (subject_id, e.g. identity:<id>).
 */
export const checkRelationship = <ThrowOnError extends boolean = false>(options: Options<CheckRelationshipData, ThrowOnError>): RequestResult<CheckRelationshipResponses, unknown, ThrowOnError> => (options.client ?? client).post<CheckRelationshipResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/checkRelationship',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ensure a graph relationship exists
 *
 * Idempotently create a relationship in the authorization graph (Ory Keto). Used by domain services to grant permissions and role members.
 */
export const ensureRelationship = <ThrowOnError extends boolean = false>(options: Options<EnsureRelationshipData, ThrowOnError>): RequestResult<EnsureRelationshipResponses, unknown, ThrowOnError> => (options.client ?? client).post<EnsureRelationshipResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/ensureRelationship',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a graph relationship
 *
 * Idempotently delete a relationship from the authorization graph (Ory Keto).
 */
export const deleteRelationship = <ThrowOnError extends boolean = false>(options: Options<DeleteRelationshipData, ThrowOnError>): RequestResult<DeleteRelationshipResponses, unknown, ThrowOnError> => (options.client ?? client).post<DeleteRelationshipResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/deleteRelationship',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List graph relationships
 *
 * List stored relationships for an object in the authorization graph.
 */
export const listRelationships = <ThrowOnError extends boolean = false>(options: Options<ListRelationshipsData, ThrowOnError>): RequestResult<ListRelationshipsResponses, unknown, ThrowOnError> => (options.client ?? client).post<ListRelationshipsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/authorization/listRelationships',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
