// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | 'http://localhost:4001' | 'http://localhost:4001' | 'http://localhost:4003' | (string & {});
};

export type LoginWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/identity/login';
};

export type LoginWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified?: boolean;
        };
        sessionToken?: string;
        refreshToken?: string;
        sessionId?: string;
        expiresAt?: string;
    };
};

export type LoginWithEmailAndPasswordResponse = LoginWithEmailAndPasswordResponses[keyof LoginWithEmailAndPasswordResponses];

export type RegisterWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/identity/registerWithEmailAndPassword';
};

export type RegisterWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type RegisterWithEmailAndPasswordResponse = RegisterWithEmailAndPasswordResponses[keyof RegisterWithEmailAndPasswordResponses];

export type CreateAttachmentData = {
    body: {
        file: Blob | File;
    };
    path: {
        issueId: string;
    };
    query?: never;
    url: '/attachments/{issueId}';
};

export type CreateAttachmentErrors = {
    /**
     * Error response
     */
    400: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
    /**
     * Error response
     */
    500: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
};

export type CreateAttachmentError = CreateAttachmentErrors[keyof CreateAttachmentErrors];

export type CreateAttachmentResponses = {
    /**
     * Created successfully
     */
    201: unknown;
};
