export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  IdentityRepository: Symbol.for("IIdentityRepository"),
  IssueRepository: Symbol.for("IIssueRepository"),
  IssueAssigneeRepository: Symbol.for("IIssueAssigneeRepository"),
  IssueService: Symbol.for("IIssueService"),
  ProjectRepository: Symbol.for("IProjectRepository"),
  ProjectService: Symbol.for("IProjectService"),
  StatusRepository: Symbol.for("IStatusRepository"),
  StatusService: Symbol.for("IStatusService"),
  IdentitySyncConsumer: Symbol.for("IdentitySyncConsumer"),
} as const;
