/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as noAuthSignupRouteImport } from './../routes/(no-auth)/signup'
import { Route as noAuthLoginRouteImport } from './../routes/(no-auth)/login'

const noAuthSignupRoute = noAuthSignupRouteImport.update({
  id: '/(no-auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const noAuthLoginRoute = noAuthLoginRouteImport.update({
  id: '/(no-auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof noAuthLoginRoute
  '/signup': typeof noAuthSignupRoute
}
export interface FileRoutesByTo {
  '/login': typeof noAuthLoginRoute
  '/signup': typeof noAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(no-auth)/login': typeof noAuthLoginRoute
  '/(no-auth)/signup': typeof noAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup'
  id: '__root__' | '/(no-auth)/login' | '/(no-auth)/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  noAuthLoginRoute: typeof noAuthLoginRoute
  noAuthSignupRoute: typeof noAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(no-auth)/signup': {
      id: '/(no-auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof noAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(no-auth)/login': {
      id: '/(no-auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof noAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  noAuthLoginRoute: noAuthLoginRoute,
  noAuthSignupRoute: noAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
