/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as noAuthCallbackRouteImport } from './../routes/(no-auth)/callback'
import { Route as noAuthConsentRouteImport } from './../routes/(no-auth)/consent'
import { Route as noAuthLoginRouteImport } from './../routes/(no-auth)/login'
import { Route as noAuthSignupRouteImport } from './../routes/(no-auth)/signup'

const noAuthCallbackRoute = noAuthCallbackRouteImport.update({
  id: '/(no-auth)/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const noAuthConsentRoute = noAuthConsentRouteImport.update({
  id: '/(no-auth)/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const noAuthLoginRoute = noAuthLoginRouteImport.update({
  id: '/(no-auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const noAuthSignupRoute = noAuthSignupRouteImport.update({
  id: '/(no-auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/callback': typeof noAuthCallbackRoute
  '/consent': typeof noAuthConsentRoute
  '/login': typeof noAuthLoginRoute
  '/signup': typeof noAuthSignupRoute
}
export interface FileRoutesByTo {
  '/callback': typeof noAuthCallbackRoute
  '/consent': typeof noAuthConsentRoute
  '/login': typeof noAuthLoginRoute
  '/signup': typeof noAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(no-auth)/callback': typeof noAuthCallbackRoute
  '/(no-auth)/consent': typeof noAuthConsentRoute
  '/(no-auth)/login': typeof noAuthLoginRoute
  '/(no-auth)/signup': typeof noAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/callback' | '/consent' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/callback' | '/consent' | '/login' | '/signup'
  id:
    | '__root__'
    | '/(no-auth)/callback'
    | '/(no-auth)/consent'
    | '/(no-auth)/login'
    | '/(no-auth)/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  noAuthCallbackRoute: typeof noAuthCallbackRoute
  noAuthConsentRoute: typeof noAuthConsentRoute
  noAuthLoginRoute: typeof noAuthLoginRoute
  noAuthSignupRoute: typeof noAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(no-auth)/callback': {
      id: '/(no-auth)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof noAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(no-auth)/consent': {
      id: '/(no-auth)/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof noAuthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(no-auth)/login': {
      id: '/(no-auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof noAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(no-auth)/signup': {
      id: '/(no-auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof noAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  noAuthCallbackRoute: noAuthCallbackRoute,
  noAuthConsentRoute: noAuthConsentRoute,
  noAuthLoginRoute: noAuthLoginRoute,
  noAuthSignupRoute: noAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
