export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  HttpServer: Symbol.for("IHttpServer"),
  AuthorizationClient: Symbol.for("IAuthorizationClient"),
  TenantRepository: Symbol.for("ITenantRepository"),
  TenantService: Symbol.for("ITenantService"),
  TenantRelationService: Symbol.for("ITenantRelationService"),
  OrganizationRepository: Symbol.for("IOrganizationRepository"),
  OrganizationService: Symbol.for("IOrganizationService"),
  OrganizationRelationService: Symbol.for("IOrganizationRelationService"),
  PlatformRelationService: Symbol.for("IPlatformRelationService"),
  IdentityRepository: Symbol.for("IIdentityRepository"),
  IdentityService: Symbol.for("IIdentityService"),
  PlatformIdentitySyncConsumer: Symbol.for("PlatformIdentitySyncConsumer"),
} as const;
