export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  HttpServer: Symbol.for("IHttpServer"),
  AuthorizationClient: Symbol.for("IAuthorizationClient"),
  TenantRepository: Symbol.for("ITenantRepository"),
  TenantService: Symbol.for("ITenantService"),
  OrganizationRepository: Symbol.for("IOrganizationRepository"),
  OrganizationService: Symbol.for("IOrganizationService"),
  PlatformRoleRepository: Symbol.for("IPlatformRoleRepository"),
  PlatformRoleService: Symbol.for("IPlatformRoleService"),
  PlatformRoleAssignmentRepository: Symbol.for("IPlatformRoleAssignmentRepository"),
  PlatformRoleAssignmentService: Symbol.for("IPlatformRoleAssignmentService"),
  CapabilityRepository: Symbol.for("ICapabilityRepository"),
  CapabilityService: Symbol.for("ICapabilityService"),
} as const;
