// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | 'http://localhost:4001' | 'http://localhost:4001' | 'http://localhost:4001' | 'http://localhost:4001' | 'http://localhost:4001' | 'http://localhost:4003' | (string & {});
};

export type LoginWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/identity/login';
};

export type LoginWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified?: boolean;
        };
    };
};

export type LoginWithEmailAndPasswordResponse = LoginWithEmailAndPasswordResponses[keyof LoginWithEmailAndPasswordResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/logout';
};

export type LogoutResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/me';
};

export type GetCurrentUserResponses = {
    /**
     * Default Response
     */
    200: {
        identity: {
            id: string;
            email: string;
            emailVerified?: boolean;
        };
    };
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type AuthorizeData = {
    body?: never;
    path?: never;
    query: {
        responseType: 'code';
        clientId: string;
        redirectUri: string;
        scope: string;
        state: string;
        codeChallenge?: string;
        codeChallengeMethod?: 'S256' | 'plain';
        nonce?: string;
    };
    url: '/identity/oauth/authorize';
};

export type AuthorizeResponses = {
    /**
     * Default Response
     */
    200: {
        redirectTo: string;
    };
};

export type AuthorizeResponse = AuthorizeResponses[keyof AuthorizeResponses];

export type RegisterWithEmailAndPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/identity/registerWithEmailAndPassword';
};

export type RegisterWithEmailAndPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type RegisterWithEmailAndPasswordResponse = RegisterWithEmailAndPasswordResponses[keyof RegisterWithEmailAndPasswordResponses];

export type CreateAttachmentData = {
    body: {
        file: Blob | File;
    };
    path: {
        issueId: string;
    };
    query?: never;
    url: '/attachments/{issueId}';
};

export type CreateAttachmentErrors = {
    /**
     * Error response
     */
    400: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
    /**
     * Error response
     */
    500: {
        message: string;
        statusCode?: number;
        [key: string]: unknown;
    };
};

export type CreateAttachmentError = CreateAttachmentErrors[keyof CreateAttachmentErrors];

export type CreateAttachmentResponses = {
    /**
     * Created successfully
     */
    201: unknown;
};
