export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  IdentityRepository: Symbol.for("IIdentityRepository"),
  IdentitySyncConsumer: Symbol.for("IdentitySyncConsumer"),
  RoleRepository: Symbol.for("IRoleRepository"),
  RoleCapabilityRepository: Symbol.for("IRoleCapabilityRepository"),
  RoleAssignmentRepository: Symbol.for("IRoleAssignmentRepository"),
  RoleAssignmentService: Symbol.for("IRoleAssignmentService"),
  RoleAssignmentKetoSyncConsumer: Symbol.for("RoleAssignmentKetoSyncConsumer"),
  RoleService: Symbol.for("IRoleService"),
  ResourceRepository: Symbol.for("IResourceRepository"),
  CapabilityRepository: Symbol.for("ICapabilityRepository"),
  CapabilityService: Symbol.for("ICapabilityService"),
  AuthorizationService: Symbol.for("IAuthorizationService"),
  KetoClient: Symbol.for("KetoClient"),
  AuthorizationGraphProvider: Symbol.for("IAuthorizationGraphProvider"),
} as const;
