export const TYPES = {
  Database: Symbol.for("Database"),
  Logger: Symbol.for("Logger"),
  Broker: Symbol.for("Broker"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  RoleRepository: Symbol.for("IRoleRepository"),
  RoleResourceRepository: Symbol.for("IRoleResourceRepository"),
  RoleAssignmentRepository: Symbol.for("IRoleAssignmentRepository"),
  RoleAssignmentService: Symbol.for("IRoleAssignmentService"),
  RoleAssignmentKetoSyncConsumer: Symbol.for("RoleAssignmentKetoSyncConsumer"),
  RoleService: Symbol.for("IRoleService"),
  ResourceRepository: Symbol.for("IResourceRepository"),
  ResourceRelationRepository: Symbol.for("IResourceRelationRepository"),
  PermissionRepository: Symbol.for("IPermissionRepository"),
  PermissionService: Symbol.for("IPermissionService"),
  AuthorizationService: Symbol.for("IAuthorizationService"),
  KetoClient: Symbol.for("KetoClient"),
  AuthorizationGraphProvider: Symbol.for("IAuthorizationGraphProvider"),
} as const;
