export const TYPES = {
  Database: Symbol.for("Database"),
  Broker: Symbol.for("Broker"),
  Logger: Symbol.for("Logger"),
  Publisher: Symbol.for("Publisher"),
  OutboxRepository: Symbol.for("IOutboxRepository"),
  OutboxService: Symbol.for("IOutboxService"),
  RetryPolicy: Symbol.for("IRetryPolicy"),
  OutboxWorker: Symbol.for("IOutboxWorker"),
  OutboxCleanupService: Symbol.for("IOutboxCleanupService"),
  OutboxCleanupWorker: Symbol.for("IOutboxCleanupWorker"),
  AttachmentScanRepository: Symbol.for("IAttachmentScanRepository"),
  AttachmentScannerService: Symbol.for("IAttachmentScannerService"),
  AttachmentQuarantinedConsumer: Symbol.for("AttachmentQuarantinedConsumer"),
  AttachmentClient: Symbol.for("IAttachmentClient"),
  MalwareScanner: Symbol.for("IMalwareScanner"),
  MalwareScannerService: Symbol.for("IMalwareScannerService"),
  ClamClient: Symbol.for("ClamClient"),
};
