// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, useMutation, type UseMutationOptions, useQuery } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getIdentityGetSession, getIdentityGetTokenSession, getIdentityMe, getIdentityOauthAuthorize, getIdentityOauthConsent, getIdentityVerifyEmail, type Options, postAttachmentsByIssueId, postIdentityLogout, postIdentityOauthConsentAccept, postIdentityOauthConsentReject, postIdentityOauthToken, postIdentityRegister, postIdentityResendVerificationEmail, postIdentitySignin } from '../sdk.gen';
import type { GetIdentityGetSessionData, GetIdentityGetTokenSessionData, GetIdentityMeData, GetIdentityOauthAuthorizeData, GetIdentityOauthConsentData, GetIdentityVerifyEmailData, PostAttachmentsByIssueIdData, PostIdentityLogoutData, PostIdentityOauthConsentAcceptData, PostIdentityOauthConsentRejectData, PostIdentityOauthTokenData, PostIdentityRegisterData, PostIdentityResendVerificationEmailData, PostIdentitySigninData } from '../types.gen';

export const postIdentitySigninMutation = (options?: Partial<Options<PostIdentitySigninData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentitySigninData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentitySigninData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postIdentitySignin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostIdentitySigninMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentitySigninData>>, 'mutationFn'>>) => useMutation({ ...postIdentitySigninMutation(), ...mutationOptions });

export const postIdentityLogoutMutation = (options?: Partial<Options<PostIdentityLogoutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postIdentityLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostIdentityLogoutMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityLogoutData>>, 'mutationFn'>>) => useMutation({ ...postIdentityLogoutMutation(), ...mutationOptions });

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getIdentityMeQueryKey = (options?: Options<GetIdentityMeData>) => createQueryKey('getIdentityMe', options);

export const getIdentityMeOptions = (options?: Options<GetIdentityMeData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getIdentityMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityMeQueryKey(options)
});

export const useGetIdentityMeQuery = (options?: Options<GetIdentityMeData>) => useQuery(getIdentityMeOptions(options));

export const getIdentityGetSessionQueryKey = (options?: Options<GetIdentityGetSessionData>) => createQueryKey('getIdentityGetSession', options);

export const getIdentityGetSessionOptions = (options?: Options<GetIdentityGetSessionData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getIdentityGetSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityGetSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityGetSessionQueryKey(options)
});

export const useGetIdentityGetSessionQuery = (options?: Options<GetIdentityGetSessionData>) => useQuery(getIdentityGetSessionOptions(options));

export const getIdentityGetTokenSessionQueryKey = (options?: Options<GetIdentityGetTokenSessionData>) => createQueryKey('getIdentityGetTokenSession', options);

export const getIdentityGetTokenSessionOptions = (options?: Options<GetIdentityGetTokenSessionData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getIdentityGetTokenSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityGetTokenSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityGetTokenSessionQueryKey(options)
});

export const useGetIdentityGetTokenSessionQuery = (options?: Options<GetIdentityGetTokenSessionData>) => useQuery(getIdentityGetTokenSessionOptions(options));

export const getIdentityOauthAuthorizeQueryKey = (options?: Options<GetIdentityOauthAuthorizeData>) => createQueryKey('getIdentityOauthAuthorize', options);

export const getIdentityOauthAuthorizeOptions = (options?: Options<GetIdentityOauthAuthorizeData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getIdentityOauthAuthorizeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityOauthAuthorize({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityOauthAuthorizeQueryKey(options)
});

export const useGetIdentityOauthAuthorizeQuery = (options?: Options<GetIdentityOauthAuthorizeData>) => useQuery(getIdentityOauthAuthorizeOptions(options));

export const getIdentityOauthConsentQueryKey = (options?: Options<GetIdentityOauthConsentData>) => createQueryKey('getIdentityOauthConsent', options);

export const getIdentityOauthConsentOptions = (options?: Options<GetIdentityOauthConsentData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getIdentityOauthConsentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityOauthConsent({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityOauthConsentQueryKey(options)
});

export const useGetIdentityOauthConsentQuery = (options?: Options<GetIdentityOauthConsentData>) => useQuery(getIdentityOauthConsentOptions(options));

export const postIdentityOauthConsentAcceptMutation = (options?: Partial<Options<PostIdentityOauthConsentAcceptData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthConsentAcceptData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthConsentAcceptData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postIdentityOauthConsentAccept({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostIdentityOauthConsentAcceptMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthConsentAcceptData>>, 'mutationFn'>>) => useMutation({ ...postIdentityOauthConsentAcceptMutation(), ...mutationOptions });

export const postIdentityOauthConsentRejectMutation = (options?: Partial<Options<PostIdentityOauthConsentRejectData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthConsentRejectData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthConsentRejectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postIdentityOauthConsentReject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostIdentityOauthConsentRejectMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthConsentRejectData>>, 'mutationFn'>>) => useMutation({ ...postIdentityOauthConsentRejectMutation(), ...mutationOptions });

export const postIdentityOauthTokenMutation = (options?: Partial<Options<PostIdentityOauthTokenData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthTokenData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postIdentityOauthToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostIdentityOauthTokenMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityOauthTokenData>>, 'mutationFn'>>) => useMutation({ ...postIdentityOauthTokenMutation(), ...mutationOptions });

export const postIdentityRegisterMutation = (options?: Partial<Options<PostIdentityRegisterData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityRegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postIdentityRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostIdentityRegisterMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityRegisterData>>, 'mutationFn'>>) => useMutation({ ...postIdentityRegisterMutation(), ...mutationOptions });

export const getIdentityVerifyEmailQueryKey = (options?: Options<GetIdentityVerifyEmailData>) => createQueryKey('getIdentityVerifyEmail', options);

export const getIdentityVerifyEmailOptions = (options?: Options<GetIdentityVerifyEmailData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getIdentityVerifyEmailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIdentityVerifyEmail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIdentityVerifyEmailQueryKey(options)
});

export const useGetIdentityVerifyEmailQuery = (options?: Options<GetIdentityVerifyEmailData>) => useQuery(getIdentityVerifyEmailOptions(options));

export const postIdentityResendVerificationEmailMutation = (options?: Partial<Options<PostIdentityResendVerificationEmailData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityResendVerificationEmailData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityResendVerificationEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postIdentityResendVerificationEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostIdentityResendVerificationEmailMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostIdentityResendVerificationEmailData>>, 'mutationFn'>>) => useMutation({ ...postIdentityResendVerificationEmailMutation(), ...mutationOptions });

export const postAttachmentsByIssueIdMutation = (options?: Partial<Options<PostAttachmentsByIssueIdData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostAttachmentsByIssueIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostAttachmentsByIssueIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAttachmentsByIssueId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usePostAttachmentsByIssueIdMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostAttachmentsByIssueIdData>>, 'mutationFn'>>) => useMutation({ ...postAttachmentsByIssueIdMutation(), ...mutationOptions });
