mutation DeleteAttachment($deleteAttachmentId: String!) {
  deleteAttachment(id: $deleteAttachmentId)
}

query FindAttachments($issueId: String!) {
  findAttachments(issueId: $issueId) {
    rowCount
    rows {
      id
      thumbnailLink
    }
  }
}
