mutation CreateList($input: CreateListInput!) {
  createList(input: $input)
}

query FindList($findListId: String!) {
  findList(id: $findListId) {
    id
    name
  }
}

query FindLists {
  findLists {
    rows {
      id
      name
      space {
        id
        name
      }
    }
    rowCount
  }
}

query FindStatuses($input: FindStatusesOptions!) {
  findStatuses(input: $input) {
    id
    name
  }
}

query FindCustomFields($options: FindCustomFieldsOptions!) {
  findCustomFields(options: $options) {
    customFieldId
    id
    listId
  }
}
