mutation CreateSpace($input: CreateSpaceInput!) {
  createSpace(input: $input)
}

query FindSpaces($input: FindSpacesOptions!) {
  findSpaces(input: $input) {
    id
    name
    lists {
      id
      name
      selectedViewId
      space {
        name
      }
    }
  }
}
